Epistimio/orion

README.md

I thought I saw all the possible variants, but Boulithier is a new one! XD

Fix my name ^_^

---

.travis.yml
README.md
RESEARCH.md
setup.py

See #2 for summary of 1st meeting. Adjusting README.md and RESEARCH.md for implications.

Adjusting to meeting#1

---

.travis.yml
CMakeLists.txt
src/metaopt.cpp
src/metaoptd.cpp

- adding working CMakeLists.txt
- tested build nightly on Ubuntu 14.04
- added metaopt.cpp for client
- metaoptd.cpp for daemon service that does process fork on Linux"
TODO
- adding ring buffer data structure from LMAX Disruptor to metaoptd, to efficiently receive orders and executes experiments from `metaopt` client 
- adding UDP communication broadcast support
- adding MongoDB database

Proof of Concept of Python Process Forking on metaoptd (daemon)

---

CMakeLists.txt

```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
CMake 3.8.0 or higher is required.  You are running version 3.7.2
```

Update CMakeLists.txt to accomodate TravisCI build

---

.travis.yml
CMakeLists.txt

passing in Boost_libraries instead in CMakeLists

patching error Boost program options not found

---

src/metaopt/io/database/__init__.py
src/metaopt/io/database/mongodb.py
tests/core/unittests/mongodb_test.py

Close mila-udem/metaopt#19: AbstractDB.read rets list

---

.pylintrc
src/metaopt/cli.py
src/metaopt/io/database/__init__.py
src/metaopt/io/database/mongodb.py
src/metaopt/resolve_config.py
src/metaopt/worker/experiment.py
src/metaopt/worker/trial.py
tests/core/unittests/conftest.py
tests/core/unittests/database_test.py
tests/core/unittests/experiment.yaml
tests/core/unittests/mongodb_test.py
tests/core/unittests/test_experiment.py
tests/core/unittests/test_trial.py
tox.ini

This branch must be merged after #18.

Feature: Implement Experiment & Trial class

---

src/orion/core/cli.py
src/orion/core/resolve_config.py
tests/functional/demo/test_demo.py

Also, fix a minor bug in hierarchical configuration.

Make `random` algorithm be the default choice

---

src/metaopt/core/worker/transformer.py
src/orion/algo/base.py
src/orion/algo/space.py
src/orion/core/worker/primary_algo.py
src/orion/core/worker/transformer.py
tests/conftest.py
tests/functional/gradient_descent_algo/src/orion/algo/gradient_descent.py
tests/unittests/algo/test_space.py
tests/unittests/core/test_transformer.py

Also, implement them in PrimaryAlgo whose responsibility is exactly that.
Currently, this PR is not complete.
Missing:

Feature: Add transformations of points, Dimension, Space, and a builder for that

---

docs/src/database.rst

Revert "Update database.rst"

---

docs/src/user/defining.rst
docs/src/user/pytorch.rst

Improve docs

---

docs/src/examples/pytorch_a2c_ppo.rst
docs/src/examples/pytorch_cifar.rst
docs/src/index.rst
setup.py

I think this is the rebased version of the previous PR, please double check that this doesn't mess anything up.

Add RL example

---

README.rst

Fix broken link in readme

---

docs/src/install/database.rst
src/orion/core/cli/setup.py
tests/functional/commands/test_setup_command.py
tests/unittests/core/cli/test_checks.py
tests/unittests/core/io/convert_test.py
tests/unittests/core/io/test_cmdline_parser.py

Add the `setup` command

---

docs/src/code/core/cli.rst
docs/src/code/core/cli/setup.rst
docs/src/code/core/cli/test_db.rst
docs/src/code/core/io/database.rst
docs/src/code/core/io/database/ephemeraldb.rst
docs/src/code/core/io/database/pickleddb.rst
docs/src/examples/cluster.rst
docs/src/install/database.rst
docs/src/user/pytorch.rst
src/orion/core/cli/checks/creation.py
src/orion/core/cli/checks/presence.py
src/orion/core/cli/test_db.py

Depends on #192 
5563902 Add doc for PickledDB
7f188f9 Add doc for `test-db`
3fc9d08 Add missing working-dir and user to doc
5e4cf83 Add a note for mongodb for ssh tunnels

Clean up Documentation for release v0.1.3

---

.travis.yml
MANIFEST.in
README.rst
ROADMAP.md
setup.py
tests/functional/demo/test_demo.py
tests/functional/demo/working_dir_config.yaml
tox.ini

- Fix flake8 dependency because of pydocstyle's new release #198 
- Add continuous integration for OSX #196 
- Add RoadMap #195

Release v0.1.4rc1

---

ROADMAP.md

Why:
We needed to make a hotfix with v0.1.4 and forgot to update the roadmap accordingly

Update versions in Roadmap

---

.gitignore
src/orion/core/worker/__init__.py
src/orion/core/worker/consumer.py
src/orion/core/worker/experiment.py
tests/functional/demo/broken_box.py
tests/functional/demo/test_demo.py
tests/unittests/core/test_experiment.py

Experiment will now stop running when there are too many broken trials.

Break when broken

---

src/orion/core/cli/info.py
tests/unittests/core/cli/test_info.py

Add info command

---

docs/src/conf.py
docs/src/index.rst
docs/src/user/cli/info.rst
docs/src/user/evc.rst
docs/src/user/library/evc_results.rst
docs/src/user/library/results.rst
docs/src/user/monitoring.rst
docs/src/user/pytorch.rst

Why:
Monitoring of experiment is an important part of the usage of a tool for
hyper-parameter optimisation. There is many commands and ways to monitor
experiments using the library API, therefore it seams relevant to have a
section dedicated to this.
Why:
EVC is arguably is less important than monitoring and algorithm configuration.

Add new section Monitoring

---

src/orion/core/cli/evc.py
src/orion/core/evc/conflicts.py
src/orion/core/io/experiment_branch_builder.py
src/orion/core/io/interactive_commands/branching_prompt.py
src/orion/core/worker/experiment.py
tests/functional/branching/test_branching.py
tests/unittests/core/cli/test_evc.py
tests/unittests/core/io/interactive_commands/test_branching_prompt.py
tests/unittests/core/test_branch_config.py
tests/unittests/core/worker/test_experiment.py

Deprecate `--auto-resolution` and introduce `--manual-resolution`

---

src/orion/core/cli/status.py
src/orion/core/evc/experiment.py
src/orion/core/evc/tree.py
tests/functional/commands/conftest.py
tests/functional/commands/test_status_command.py

Why:
The command was not selecting last version or specifed version when
using --name.

Fix orion status --name --version

---

src/orion/client/experiment.py
tests/unittests/client/test_experiment_client.py

Why:
If the process exits, the trial status stays to `reserved` and will
eventually be set to `interrupted`.
How:
Register a function to release the remaining trials with pacemakers. If
the process exits normally (no signup signals or sigterm), the function
will be called and all reserved trials will be set to broken.

Handle broken trials with python API

---

setup.py
src/orion/algo/hyperband.py
tests/functional/algos/hyperband.yaml
tests/functional/algos/test_algos.py
tests/unittests/algo/test_hyperband.py

Move hyperband from a separate algorithms plugin [orion.core.hyeprband](https://github.com/Epistimio/orion.algo.hyperband) to an OOB algorithms in Orion core.

Hyperband oob

---

src/orion/algo/base.py
src/orion/algo/random.py
src/orion/core/worker/primary_algo.py
src/orion/core/worker/producer.py
tests/conftest.py
tests/unittests/algo/test_base.py

Provide a default cardinality check in base algorithm. Any algorithm which does not want to use this will have to override is_done. 
@bouthilx

Generic cardinality check in base algorithm

---

docs/src/developer/overview.rst
docs/src/examples/scikit-learn.rst

Following the feedback of https://github.com/Epistimio/orion/pull/366, I removed the remaining relative links in the documentation.
Please squash and merge this PR :).

Remove relative links

---

README.rst

This pull request is meant to be a discussion about how we can improve the current list of features to serve as a presentation of Oríon's moto and strong points (or core concepts). 
The current description is too factual (i.e., the information is too specific for an introduction aimed at new users) and somewhat confusing (e.g., some wording, redundant information with respect to the README).
My proposition revisits the moto to be more specific and impactful for newcomers but also provides a concrete design stance. Additionally, I refreshed the description items to be more engaging and to also give an overview of the strong points of our different features. Finally, I renamed the section because it was never a list of features, but more of a showcase.

Refreshed introduction of Oríon's features

---

src/orion/algo/asha.py
src/orion/algo/hyperband.py
src/orion/algo/space.py
tests/unittests/algo/test_asha.py
tests/unittests/algo/test_hyperband.py
tests/unittests/algo/test_space.py

This PR include below updates:
1) fix a bug of ASHA when the num_brackets is larger than num_rungs.  Use num_rungs as num_brackets in such cases.
2) Add cardinality check for both asha and hyperband when the algorithms failed to suggest new samples. A warning message will be logged.
@bouthilx

update asha and hyperband

---

tests/unittests/algo/test_tpe.py

Fix the output of random output from gmm sampler so the assert left/right is relative fixed too.

Update tpe test case

---

docs/src/plugins/algorithms.rst
docs/src/plugins/base.rst

The doc was referring to the test algo gradient descent instead of
reusing the extensive documentation of the cookiecutter.

Update Plugins documentation section

---

docs/src/code/core/io/database/ephemeraldb.rst
docs/src/developer/testing.rst
docs/src/install/database.rst

This pull request refreshes and improves the database configuration documentation to make it easier to read and navigate.
This updated documentation is streamlined toward giving the users the information they need quickly whether it's their first time seeing the page or the hundredth.
- Regrouped common information in sections or subsections.
- Reordered sections
- Fixed typos
- Reworded some sentences
- Removed outdated information

Refresh database documentation

---

src/orion/core/io/config.py
tests/unittests/core/io/test_config.py

Why:
Some options (like algorithm configuration) have a dict type. The
load_yaml was failing on such configuration because flatten would break
the structure of the configuration, looking at the subkeys of the item's
dictionary as if they were options in the global configuration.
How:
Turn the load_yaml into a recursive function that is called on each
subconfig. This way dictionary items (like algo conf) are not unpacked
and thus processed properly.

Support load yaml config for dict items

---

.github/workflows/build.yml
conda/ci_build.sh
tox.ini

Add support for python 3.9

---

tests/unittests/core/test_transformer.py

[Fixes #515]
The precision is applied in both directions (transform and reverse). I don't see when it would fail to round properly, except maybe rounding errors in python.
This adds a test for precision with linearization, which is the most likely scenario where it may fail.

Test that precision isn't messed up by linearization

---

src/orion/core/evc/conflicts.py

Add more logging when branching

---

src/orion/core/cli/hunt.py
src/orion/core/worker/__init__.py
src/orion/core/worker/consumer.py
tests/functional/branching/test_branching.py
tests/functional/configuration/test_all_options.py

Set ignore_code_changes in Consumer too

---

docs/src/code/algo.rst
docs/src/code/algo/gridsearch.rst
docs/src/user/algorithms.rst
setup.py
src/orion/algo/gridsearch.py
src/orion/algo/space.py
src/orion/algo/tpe.py
src/orion/core/io/experiment_builder.py
src/orion/core/worker/producer.py
src/orion/core/worker/transformer.py
tests/functional/algos/test_algos.py
tests/unittests/algo/test_gridsearch.py
tests/unittests/algo/test_tpe.py
tests/unittests/core/worker/test_producer.py

Add grid search algorithm

---

docs/src/install/database.rst
docs/src/tutorials/pytorch-mnist.rst
docs/src/tutorials/pytorch_a2c_ppo.rst
docs/src/tutorials/pytorch_cifar.rst
docs/src/user/config.rst
src/orion/core/__init__.py
src/orion/core/io/database/__init__.py
src/orion/core/io/database/mongodb.py
src/orion/core/io/database/pickleddb.py
src/orion/core/utils/pptree.py
tests/functional/benchmark/test_benchmark_flow.py
tests/functional/serving/test_trials_resource.py
tests/unittests/core/io/test_resolve_config.py
tests/unittests/core/mongodb_test.py
tests/unittests/core/test_branch_config.py

Change the default database to PickledDB

---

docs/src/install/gettingstarted.rst
docs/src/user/config.rst
docs/src/user/evc.rst

Add missing documentation for EVC enable option

---

src/orion/plotting/backend_plotly.py

Signed-off-by: Fabrice Normandin <fabrice.normandin@gmail.com>

Fix grouping of plots in legend

---

tests/unittests/core/database/test_database.py

replace count by count_documents #706 

---

src/orion/algo/space.py

Replace np.object by object; np.object is deprecated

---

.github/workflows/build.yml
conda/ci_build.sh
setup.py
tox.ini

Title.
This is going to enable us to use nice type hints everywhere thanks to https://peps.python.org/pep-0563/

Drop support for python 3.6

---

.github/workflows/build.yml

Is this sufficient @bouthilx ? Or do I need to change something else?

Upgrade default python to 3.9 in build.yaml

---

tests/functional/client/orion_config.yaml
tests/functional/demo/database_config.yaml
tests/functional/demo/orion_config.yaml
tests/functional/demo/orion_config_other.yaml
tests/functional/demo/strategy_config.yaml
tests/functional/demo/stress_gradient.yaml
tests/functional/demo/working_dir_config.yaml
tests/functional/parsing/orion_config_random.yaml

Tests should use PickledDB by default

Remove remaining mongodb configs

---

src/orion/core/worker/consumer.py
tests/functional/demo/black_box.py
tests/functional/demo/orion_black_box.py
tests/functional/demo/test_demo.py

Revert Subprocess pipe

---

conda/meta.yaml

PR #998 was missing the downgrade in conda build.

Downgrade pandas in conda build too
