Epistimio/orion

src/metaopt/utils/_appdirs.py
- It broke when trying to install to a virtualenv.
Referring issue #16.
=> Appdirs: Fix site_data_dirs for OS X to prefer `sys.prefix` too

src/metaopt/core/io/database/mongodb.py, tests/unittests/core/mongodb_test.py
Why:
Unittest for bad connections takes several seconds, more than the sum of
all other unit tests. This is only due to a default large Timeout inside
pymongo when server does not respond.
How:
Mock pymongo's MongoClient to force serverSelectionTimeoutMS to 1.
=> Decrease unittest time for database

src/metaopt/core/io/database/__init__.py, src/metaopt/core/io/database/mongodb.py, src/metaopt/core/worker/experiment.py, tests/unittests/core/mongodb_test.py, tests/unittests/core/test_experiment.py
Related to #10, #14 and #42
Needs #36 to be merged.
1. Add `read_and_write()` to `Database`
2. Use `read_and_write()` instead of `write()` to reserve trials inside `Experiment.reserve_trial()`
Why:
Some operations require atomicity. For instance, when selecting a new trial, between the first read to database, the potential scoring and the random selection, another process could reserve it concurrently. To avoid such concurrency problems, we must ensure at the update time that the status was not altered during the selection.
How:
Using `read_and_write()` can ensure atomic operations. At update time, the process only proceed to update if the selected document remained unaltered. In our specific case, we could look at the status, since by design  only "reserved" trials can possibly change. …
=>  Fix race condition for experiment trial selection

src/metaopt/core/cli.py, src/metaopt/core/io/database/__init__.py, src/metaopt/core/io/database/mongodb.py, src/metaopt/core/worker/experiment.py, tests/unittests/core/experiment.yaml, tests/unittests/core/mongodb_test.py, tests/unittests/core/test_experiment.py
Related to #10, #14 and #41 .
Needs #36 and #53 to be merged.
Our main and only database back end is a NoSQL one and only `_id` is indexed by default. That means every `read` operation (including reads necessary in updates with queries) needs to parse the entire collection unless the query specifies the _id. This is highly inefficient. Adding indexes on keys which are often used in queries will significantly improve the database operations.
Additionally, we want to force some keys to be unique, namely the tuple (experiment name, user name). To do so we need a method to specify unique indexes.
- Experiments are believed to be mostly queried by (name, user) or status, so those keys are indexed.
- Trials are mostly queried by experiment, status, results, start_time or end_time.
- Keys can be …
=> Add indexation to databases and fix race condition for experiment configuration

docs/requirements.txt
Fix master branch.
- Breaks for sphinx == 1.7.3
I don't know why. :sweat_smile:
Note: This is to allow merging #58, #62 and #63 without waiting for #59 .
=> Freeze sphinx to at most 1.7.3

src/orion/core/io/space_builder.py, src/orion/core/worker/consumer.py, src/orion/core/worker/trial.py, tests/functional/demo/dir_per_trial.py, tests/functional/demo/stress_gradient.yaml, tests/functional/demo/test_demo.py, tests/functional/gradient_descent_algo/src/orion/algo/gradient_descent.py, tests/unittests/core/mongodb_test.py, tests/unittests/core/test_space_builder.py, tests/unittests/core/test_trial.py
Why:
I need to way to identify saved stuff in local disk from the
execution of my script given a particular trial. This way I can have
a reproducible deterministic string identifier that I intend to pass
appropriately to a command line argument (if specified from ``orion
hunt``) of my executable. This will disambiguate saved states,
snapshots, or logs (i.e. from tensorboard), among different trials of
the same executable.
The actual implementation of all save/load is left to the executable
itself, as well as configuring the absolute path where the stuff will
be saved to. Most (responsible) ML programs I have personally encountered
have a cli way to specify some naming for the experiment to run.
=> User can request managerial info, like trial string identifiers, from cli

README.rst
Note: PR on **develop**
Why:
Links for the documentation could not be inferred before the readthedocs
account was online. Now that we have those links, they are added to the
README file.
=> Add full ref to README

src/orion/core/evc/__init__.py, src/orion/core/evc/adapters.py, src/orion/core/worker/trial.py, tests/unittests/core/evc/test_adapters.py, tests/unittests/core/test_trial.py
Depends on #86 
Why:
Experiment branches because of changes in the configuration or
the user's code. This make experiments incompatible with one another
unless we define adapters such that a branched experiment B can access
trials from parent experiment A.
How:
Adapters have two main methods, forward and backward. The method forward
defines how trials from parent experiment A are filtered or adapted to
be compatible with experiment B. Modifications are only applied at
execution time and are not saved anywhere in the database. Adapters only
provides a *view* on an experiment.
There is adapters for
* Dimension addition
* Dimension deletion
* Dimension renaming
* Change of dimension prior
* Change of algorithm
* Change of code
* Combining different adapters
Adapters all have a `to_dict` …
=> Add adapters for experiment version control

src/orion/client/manual.py, src/orion/core/cli/hunt.py, src/orion/core/cli/init_only.py, src/orion/core/cli/insert.py, src/orion/core/worker/experiment.py, tests/functional/commands/experiment.yaml, tests/functional/demo/test_demo.py, tests/unittests/core/experiment.yaml, tests/unittests/core/mongodb_test.py, tests/unittests/core/test_experiment.py
Why:
The status is not useful since properties is_done and
is_broken (coming soon) can be used to verify the state
of the experiment. As the status can be inferred, and experiments
are not very likely to be queried based on status (in opposition
to trials which are often queried based on status), there is
no reason to maintain a status attribute.
How:
Replace tests on status (which all had the function of testing if an
experiment is configured or found in DB) with test on _id.
=> Remove status attribute from Experiment

src/orion/core/evc/tree.py, tests/unittests/core/evc/test_tree.py
Why:
Experiment version control requires building trees of the experiments so
that we can fetch trials from one experiment to another or navigate from
one experiment to another to visualise different statistics.
How:
Implement a simple TreeNode and tree iterators to support the tree data
structure of the experiment version control. TreeNode is a generic class
which can carry arbitrary python objects. It comes we basic methods to
set parent and children. A method `map` allows to apply functions
recursively on the tree in a generic manner.
=> Add tree data structure for EVC 

src/orion/core/io/database/__init__.py, src/orion/core/worker/experiment.py, tests/unittests/core/conftest.py, tests/unittests/core/database_test.py, tests/unittests/core/experiment.yaml, tests/unittests/core/mongodb_test.py, tests/unittests/core/test_experiment.py, tests/unittests/core/test_producer.py
Why:
With experiment version control there is the possibility of having many
experiments instantiated at the same time but only one should be
editable, the main one. All the others should not be able to make
modifications in the database. This commit is an attempt at reducing
write errors by wrapping the experiment with a read-only wrapper which
defines which attributes can be accessed and which not.
Note:
It will still be possible to access the write methods of the experiment,
by explicitly fetching it with by accessing the sub attribute of the
wrapper (ex: experiment_view._experiment.register_trials()).
Nonetheless the current wrapper makes it less likely to do so by error.
How:
Create an empty class with a valid_attributes. list which defines which
attribute and method may be accessed. …
=> Add ExperimentView and ReadOnlyDB wrapper

src/orion/algo/space.py, src/orion/core/utils/format_trials.py
**Case**:
Use random optimization for a single (3,)-shaped dimension.
**Reproduce**:
In bouthilx/orion.algo.skopt#3 run:
```
export ORION_DB_NAME=orion_test
export ORION_DB_ADDRESS=mongodb://user:pass@localhost
orion -n=test --pool-size=1 --max-trials=10 ./tests/rosenbrock.py -x~'uniform(-5, 5, shape=3)'
```
**Traceback**:
from ``worker.__init__.py``:line 42 (workon)
``producer.produce()``
from ``worker.experiment.py``:line 228 (register_trials)
``self._db.write('trials', trials_dicts)``
from ``mongodb.py``:line 41 (write)
``result = dbcollection.insert_many(documents=data)``
**Raises**:
``bson.errors.InvalidDocument: Cannot encode object: array([0.8, 1.3])``
=> Fix: Convert ndarrays to lists because they are not bsonable

src/orion/core/io/database/mongodb.py, tests/unittests/core/mongodb_test.py
This PR gives support for options necessary for the use of Atlas MongoDB DaaS or the database at Mila.
`MongoDB` would only pass host, port, username and password to `MongoClient`. The user could not use any option like `ssl` or `replicaSet`.
Support for options are mandatory to access secured databases.
Pass the URI rather than the parsed host when specified by the user.
There is no support for specific options through the interface. Options need to be specified in the URI for now.
`pymongo` would overwrite single arguments passed by those in the URI if they are different. The behavior of `MongoDB` is reversed in this commit to be coherent with `pymongo`.
=> Adapt MongoDB to support options

src/orion/core/cli/base.py, src/orion/core/io/database/ephemeraldb.py, src/orion/core/io/experiment_builder.py, tests/unittests/core/test_ephemeraldb.py
It is tedious to debug with orion when using a database, especially when many modifications of invocations keep generating experiment branching events. With the EphemeralDB, we can isolate invocations and make the debugging process smoother.
When --debug is specified, the dbtype of the config is overwritten with 'ephemeraldb'
See commit message cfb0bd9 for more information about the EphemeralDB
=> Add --debug option to isolate command line invocations

src/orion/core/cli/base.py
Currently `-vvv` corresponds to zero level of verbosity which is not very intuitive. I refactored this part, now verbosity >=2 corresponds to `DEBUG`.
=> Fix verbosity

README.rst
Now links go to `http://orion.readthedocs.io/en/latest/github.com/mila-udem/orion` for example.
=> Fix github links

src/orion/core/cli/hunt.py, src/orion/core/io/resolve_config.py, src/orion/core/worker/__init__.py, tests/functional/parsing/test_parsing_hunt.py
Why:
-----
Sometimes it is desirable to limit number of trials to run on a specific node without changing the total number of trials for the whole experiment. For example, one could run only one trial per node on a cluster with `max_trials` set to some value. This helps to schedule jobs better on a cluster.
How:
-----
`--worker-trials` affects only a specific worker. The worker exits when either `max_trials` for the experiment reached or `worker_trials`.
=> Add `hunt --worker-trials` argument

.travis.yml, docs/src/developer/testing.rst, tox.ini
Why:
Python 3.4 is getting old and now entered "security fixes only mode".
https://www.python.org/dev/peps/pep-0429/#id4
3.4.0 final: March 16, 2014
https://www.python.org/downloads/release/python-349/
> Python 3.4.9
> Release Date: 2018-08-02
>
> Python 3.4.9 was released on August 2nd, 2018.
>
> Python 3.4 has now entered "security fixes only" mode, and as such the
> only changes since Python 3.4.7 are security fixes. Also, Python 3.4.9
> has only been released in source code form; no more official binary
> installers will be produced.
> There are no specific plans for the next release of Python 3.4.
> However, the expectation is that Python 3.4.10 will be released in March
> of 2019, and this will be the final release of Python 3.4.
How:
Python 3.7 is supported as-is. Only modification …
=> Drop support for py34 and add py37

src/orion/core/worker/experiment.py
In reference to: https://github.com/Epistimio/orion/issues/143
(I made a PR earlier but closed it since I forked off the wrong branch. And then git was being problematic on the MILA servers! It should be good now.)
=> Add node property

src/orion/core/io/database/mongodb.py, tests/unittests/core/mongodb_test.py
Why:
The method count() is now deprecate in pymongo.
How:
Use count_documents() instead.
=> Fix mongodb count deprecation

src/orion/core/io/resolve_config.py, src/orion/core/worker/experiment.py, tests/unittests/core/io/test_resolve_config.py
Why:
We decided that Oríon would crash if the script being executed is not part of a code version control (only support git for now). This was to ensure reproducibility, but this constraint is troublesome for users using a different VCS system or none at all. It's not Oríon's role to enforce a VCS on users. They could at least use Oríon without `git`, they will only loose the automatic code change detection.
How:
Log a warning that code change cannot be detected instead of raising an error.
=> Relax constraint for git repository

src/orion/algo/base.py, src/orion/algo/random.py, src/orion/core/worker/primary_algo.py, src/orion/core/worker/producer.py, src/orion/core/worker/strategy.py, tests/conftest.py, tests/functional/commands/experiment.yaml, tests/functional/demo/strategy_config.yaml, tests/functional/demo/test_demo.py, tests/unittests/algo/test_base.py, tests/unittests/algo/test_random.py, tests/unittests/core/experiment.yaml, tests/unittests/core/io/orion_old_config.yaml, tests/unittests/core/io/test_experiment_builder.py, tests/unittests/core/test_experiment.py, tests/unittests/core/test_primary_algo.py, tests/unittests/core/test_producer.py, tests/unittests/core/test_strategy.py
Some (if not many) algorithms are random and should be _seedable_.
Add the method `seed_rng()` which may seed the algorithm's interval
random number generator. For flexibility, the implementation of the
seeding mechanism is speficic to each algorithm and there is no standard
`RNG` object made public.
The methods `Strategy.observe` were expecting results as `Result` type,
but were being passed results as dictionaries.
Since Algorithm.observe gets results as dictionaries, we keep the same
for `Strategy` for coherence.
=> Add seeding to algorithm and fix parallel strategies

src/orion/core/cli/base.py, src/orion/core/io/experiment_builder.py, src/orion/core/io/resolve_config.py, src/orion/core/worker/experiment.py, tests/unittests/core/io/test_experiment_builder.py, tests/unittests/core/test_experiment.py
Why:
The user's name is defined based on the OS's username (`getpass.getuser()`), but a same user may run the experiment on different systems using different usernames. There should be a way to override to default `getpass.getuser()` and pass a username to Oríon to support such use-cases. This is also true if different users wants to collaborate and fetch results from a colleague.
How:
Username can be passed in config or as `--user`. The name is then passed to either `Experiment` or `ExperimentView` in the `ExperimentBuilder`.
Note:
Maybe we should remove the username from the experiment altogether in the future.
=> Make experiment's user customisable

src/orion/core/worker/experiment.py, tests/functional/branching/test_branching.py, tests/unittests/core/test_experiment.py
Why:
The comand prompt raises OSError when the shell is non-interactive, but
for some reason it sometimes infinitely raises the OSError and
reactivate the command prompt.
How:
Raise error before starting the prompt if we detect that we are in a non
interactive shell.
=> Raise error if branching in non interactive shell

src/orion/core/worker/__init__.py, src/orion/core/worker/experiment.py, tests/functional/demo/test_demo.py
The loop in the worker was either producer or consumer, which made
worker count each production of trials as 1 trial execution. In other
words, --worker-trials 1 would execute no trial if it produced trials.
=> Fix --worker-trials

docs/src/examples/cluster.rst, docs/src/index.rst, docs/src/install/database.rst, src/orion/core/io/database/mongodb.py, src/orion/core/io/resolve_config.py, tests/unittests/core/io/test_resolve_config.py, tests/unittests/core/mongodb_test.py
Why:
SSH tunnels require a way to set ports dynamically from outside the yaml
config of orion, using env vars for instance.
How:
Add the env var ORION_DB_PORT and add tests to make sure it properly
overwrites the db host value in MongoDB.
=> Add port option for db backend

src/orion/core/io/resolve_config.py, tests/unittests/core/io/test_resolve_config.py
Why:
On OSX, hostnames cannot be interpreted by `gethostbyname()` (See #165).
How:
If the hostname cannot be interpreted, set to `localhost` by default.
=> Handle bad socket.hostname

src/orion/core/evc/conflicts.py, tests/unittests/core/conftest.py, tests/unittests/core/evc/test_conflicts.py
Why:
With the new OrionArgParser, boolean arguments are now passed with
boolean values (always True). Since we expected strings before the
change, we now need to convert the values to string in case it is a
boolean.
=> Handle bool arg in EVC Conflict

src/orion/core/io/database/ephemeraldb.py, tests/unittests/core/test_ephemeraldb.py
Why:
Sometimes a field is None which causes comparisons in queries to crash.
Comparisons with a None field should return False instead of crashing.
=> Fix null comparison in EphemeralDB

src/orion/core/worker/trial.py, tests/unittests/core/test_experiment.py, tests/unittests/core/test_trial.py
Why:
If the user pass bad results (missing objective, None objective, etc),
Oríon will later crash in mysterious ways for the users. We should
detect this early and raise an insightfull error for the user.
How:
Make the result attribute private and test in results.setter if the
provided results are valid.
=> Handle bad results in trials

src/orion/core/cli/base.py, src/orion/core/io/database/__init__.py, src/orion/core/io/database/mongodb.py, src/orion/core/io/resolve_config.py, tests/unittests/core/mongodb_test.py
Why: we were not failing fast when dealing with a non-existing
database. Now there is a default value for a timeout when connecting.
=> Add timeout for connection to Database

src/orion/algo/space.py, src/orion/core/worker/trial.py, tests/unittests/algo/test_space.py
Why:
The methods `__contains__`, `get_prior_string` and `sample` were not
implemented.
=> Add missing Fidelity methods

src/orion/algo/base.py, src/orion/algo/random.py, src/orion/core/worker/primary_algo.py, src/orion/core/worker/producer.py, tests/conftest.py, tests/unittests/algo/test_random.py, tests/unittests/core/test_producer.py
Why:
The behavior of original algo and the naive version may be different if
they have different history, leading to state increment that cannot be
synced simply but sampling and discarding from original algo. A better
way of syncing them is to provide methods state_dict/set_state so that
state can be copied over, while still discarding the lies from history.
How:
`state_dict` returns a dictionary containing required information to
reset algo state (ex: RNG state).
=> Add state_dict/set_state to algos

conda/meta.yaml, setup.py, src/orion/core/io/database/ephemeraldb.py, src/orion/core/io/database/pickleddb.py, tests/unittests/core/test_pickleddb.py
Why:
MongoDB does not play nicely with ssh tunnels and we are currently
stucked with a cluster where compute nodes does not have access to
internet, leaving us isolated from MongoDB. Using the file-system is not
optimal but it is at least simpler to set-up for the users.
How:
Simply load a pickled version of EphemeralDB and write the updated
version back to the file. All operations are locked using `filelock` to
provide support for parallel workers.
=> Add PickledDB to support FileSystem backend

docs/src/code/algo.rst, docs/src/code/algo/asha.rst, docs/src/install/plugins.rst, docs/src/user/algorithms.rst, setup.py, src/orion/algo/asha.py, src/orion/algo/random.py, src/orion/algo/space.py, src/orion/core/worker/experiment.py, src/orion/core/worker/producer.py, src/orion/core/worker/strategy.py, src/orion/core/worker/trial.py, src/orion/core/worker/trials_history.py, tests/functional/demo/test_demo.py, tests/unittests/algo/test_asha.py, tests/unittests/algo/test_space.py, tests/unittests/core/experiment.yaml, tests/unittests/core/mongodb_test.py, tests/unittests/core/test_ephemeraldb.py, tests/unittests/core/test_experiment.py, tests/unittests/core/test_pickleddb.py, tests/unittests/core/test_producer.py, tests/unittests/core/test_strategy.py, tests/unittests/core/test_trial.py, tox.ini
Seems like the most reasonable default ordering. Algos restarts may
depend on the ordering of the data for consistency (ex: ASHA).
Some algos need to know about uncompleted trials. Passing default values
like None makes it possible to detect those from inside the algorithm.
Note that this is a hack until we support iterative objectives instead
of final objectives.
Scipy's version did not support sequences for seeds. We need to support seed space that is very large so we need to support sequences.
Following numpy docstring guide, ``__init__`` should described in the class
docstring itself and therefore there is no need to document the
constructor method.
=> [WIP] Implementation of ASHA in orion.algo

.travis.yml, tests/functional/demo/test_demo.py, tests/functional/demo/working_dir_config.yaml
There should not be much differences between linux and OSX so running all our tests on both OS may be overkill. We will limit tests on OSX to `py36` test.
=> Add CI support for OSX

tox.ini
Why:
The version of pydocstyle is not upper bounded in flake8. The new
version 4.0.0 of pydocstyle is not yet supported by flake8 and won't
ever be by flake8 3.5.0.
How:
Add pydocstyle == 3.0.0 to force lower version number than what is
automatically installed when installing flake8.
=> Add pydocstyle version to tox-flake8 deps

MANIFEST.in, README.rst, ROADMAP.md, setup.py
I added a roadmap in the repo in the form of a markdown file. It is referenced from the README file and thus from the home page of the doc as well.
=> Add a roadmap to the documentation

.gitignore, src/orion/core/worker/experiment.py, src/orion/core/worker/trial.py, src/orion/core/worker/trial_monitor.py, tests/unittests/core/test_experiment.py, tests/unittests/core/worker/test_trial_monitor.py
When a trial is reserved, a heartbeat should be updated every N seconds so that we can detect if the trial is still reserved/running or lost. Currently, the wait time is configurable inside the monitoring thread, but we are waiting for the Configuration overhaul to implement it inside the configuration options.
=> Add heartbeat to Trial

src/orion/core/cli/list.py, tests/functional/commands/test_list_command.py
Why:
The argument --name was currently ignored. It should filter the name of the experiments
Why:
There is no need for a config file, what we need is to fix the DB instance in the fixture so that this one is used in all tests and not the global config or the current user running the tests.
=> Handle `orion list --name` properly

src/orion/core/worker/experiment.py, tests/unittests/core/test_experiment.py
Why:
The ExperimentView should not update the experiment in the database.
Fields doesn't get updated when loading the View per say, but loading a
view within a different version of Oríon could lead to modification of
the configuration dictionary of the experiment, which would lead to a
modified experiment in the database.
How:
Add `enable_update` argument to `Experiment.configure` so that
`ExperimentView` can call it without updating the DB.
Note:
All this should get refactored once the global and experiment
configuration refactoring is completed.
=> Skip exp update in ExpView

src/orion/core/io/database/__init__.py, src/orion/core/io/database/ephemeraldb.py, src/orion/core/io/database/mongodb.py, src/orion/core/io/database/pickleddb.py, src/orion/core/worker/experiment.py, tests/unittests/core/mongodb_test.py, tests/unittests/core/test_ephemeraldb.py, tests/unittests/core/test_experiment.py, tests/unittests/core/test_pickleddb.py
Why:
The upsert behavior was never used and was causing unexpected
DuplicateKeyError in `fix_lost_trials`. This was not observed before
because locked update with queries was previously done with
`read_and_write` in `reserve_trials` which does not update if the query
fails.
How:
Do not update if query fails and return number of updated document
instead of `result.acknowledment` so that we can verify if `db.write()`
successfully updated documents or not.
Since the current error due to race condition was not catched in
unit-tests for `fix_lost_trials()`, I added one that does catch the
error if there is a DuplicateKeyError.
=> Remove upsert from `write`

src/orion/core/io/convert.py
Why:
Since pyyaml v5.1 the function `yaml.load` prints a warning if not
called with a specified `Loader`. This is because the default behavior
was unsecure. Details about the issue are available here:
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
How:
Use `yaml.safe_load` instead which uses the SafeLoader internally.
=> Use yaml.safe_load instead of yaml

src/orion/core/evc/conflicts.py, tests/unittests/core/conftest.py, tests/unittests/core/evc/test_conflicts.py, tests/unittests/core/sample_config_diff.yml
Why:
The conflict class was looking for `orion~prior()` templates in the
values of the configuration files, but they can have other types than
strings.
=> Fix ScriptConfigConflict

tests/functional/demo/black_box_w_config.py, tests/functional/demo/script_config.yaml, tests/functional/demo/test_demo.py
The use of a config file for a user was not tested in the functional tests. I added one to make sure we cover this important use-case.
=> Add a functional test for user script config

src/orion/core/io/database/ephemeraldb.py, tests/unittests/core/test_ephemeraldb.py
Why:
The operator $ne was not supported by EphemeralDB but the operation was silently failling as a failed comparison (the field `whatever.$ne` could not exist in the document). Any unsupported operation should blatantly fail.
Why:
The operation is used in `Experiment.fetch_non_completed_trials`.
=> Add $ne and handle non-supported operation in EphemeralDB

src/orion/core/worker/experiment.py, src/orion/core/worker/producer.py, src/orion/core/worker/trials_history.py, tests/unittests/core/io/test_experiment_builder.py, tests/unittests/core/test_experiment.py, tests/unittests/core/test_producer.py, tests/unittests/core/worker/test_trials_history.py
Why:
When there is a high number of workers and communication gets slower,
it happens that fetches based on last trial's end time will miss some of
them. Since is no simple way of defining a backward internal to catch
them all, and since the actual cost of fetching all trials is relatively
cheap (which may most likely be less than 1000), it may be better to
simple fetch them all every time and filter locally.
How:
Add `__contains__` to TrialsHistory.
Move filtering in `Producer` which contains `TrialsHistory`.
Why:
There can be modifications in trials status between the call to
`fetch_completed_trials` and `fetch_noncompleted_trials`, leading
to inconsistent states, where very recently completed trials are neither
in completed trials, nor noncompleted trials. This is problematic for
ASHA, …
=> Fix race conditions during algo updates

ROADMAP.md
Remove v0.1.5 and add v0.1.7 for preliminary python API.
=> Update Roadmap for release v0.1.5

src/orion/core/cli/info.py, src/orion/core/cli/list.py, src/orion/core/worker/experiment.py, tests/functional/commands/conftest.py, tests/functional/commands/test_info_command.py, tests/functional/commands/test_list_command.py
Why:
If the process is stopped between the registration of the experiment and
the update of exp[refers][self._id], then the experiment will be somehow
broken, i.e., many code parts will crash because of it.
How:
Handle refers creation during configuration with default values if
nothing is set so that abortion during registration will in worst case
lead to inconsistant refers that is easier to fix. Previously broken
refers would be {}, which is irrecuperable for child experiments. Now
broken refers would be {parent_id: ok, adapter: ok, root_id: None},
which is simple to infer and fix.
=> Handle broken refers in experiment configuration 

src/orion/core/worker/consumer.py, src/orion/core/worker/experiment.py, src/orion/core/worker/trial_pacemaker.py, tests/functional/demo/test_demo.py, tests/unittests/core/worker/test_consumer.py, tests/unittests/core/worker/test_trial_pacemaker.py
Why:
We need access to the pacemaker when the trials is completed so that we
can stop it. Otherwise, the thread continues until if makes another
heartbeat before it crashes and quit, which can take lot of time. The
execution of Orion hangs at the end of experiment until the pacemaker
stops.
How:
Move pacemaker inside Consumer so that it can be stopped right at end of
trial execution. Note that there is some delay between the reservation
and the start of pacemaker, which makes it possible to loose the
reservation before execution begins. That is not very likely however
since there is not a large time gap between reservation and execution.
=> Move TrialMonitor/TrialPacemaker inside consumer

src/orion/algo/space.py
Why:
The plugin orion.skopt.algo is relying on these functions so we need to
keep them unless we update the plugin.
How:
Call the new methods internally and log a warning that {un}pack_point
will be removed in v0.2.0.
=> Bring back space.{un}pack_point but deprecate them

src/orion/core/io/config.py, src/orion/core/io/database/ephemeraldb.py, src/orion/core/utils/flatten.py, tests/unittests/core/io/test_config.py
Why:
The current implementation of the default > global > env var
configuration hierarchy is scattered is resolve_config and
experiment_builder. We should centralize this in an object which can
also be easily accessed from any submodule.
How:
Take blocks's Configuration class and make a few changes to support
subconfigurations.
=> Add configuration object for global configuration

src/orion/core/evc/conflicts.py, src/orion/core/worker/experiment.py, tests/functional/branching/test_branching.py, tests/unittests/core/worker/test_experiment.py
If an experiment name `root` already has at least one child not name `root`, maybe `child_1`, then it is impossible to create a new experiment name `root` to increment its version number.
While we're at it, also fixed a bug where branching from a selected version through `--version` would fail and branch from latest version.
This PR depends on #244
=> Fix problem with incrementing version on experiment with no same-named children

src/orion/core/cli/list.py, src/orion/core/evc/experiment.py, src/orion/core/worker/experiment.py, tests/functional/commands/conftest.py, tests/functional/commands/test_list_command.py, tests/functional/commands/test_status_command.py
This PR changes the output of `orion list` by adding the version of each experiment. This change has impacted `ExperimentNode` only but I decided to change `Experiment.__repr__()` anyways just because.
=> Add version to `list` output

src/orion/core/cli/info.py, src/orion/core/evc/experiment.py, src/orion/core/io/evc_builder.py, tests/functional/commands/test_info_command.py, tests/unittests/core/cli/test_info.py, tests/unittests/core/evc/test_experiment_tree.py
And fix a bug where `ExperimentNode` would enter an infinite loop. You're welcome.
=> Add support for `--version` inside `info` command

src/orion/algo/space.py, tests/unittests/algo/test_space.py
Why:
The space was supposed to have sorted keys, values and items, but `iter`
was forgotten and this caused issues in cmdline `insert` in which order
of space.keys() did not match order of `iter(space)`.
=> Fix iter(space)

src/orion/core/io/database/__init__.py, src/orion/core/io/database/ephemeraldb.py, src/orion/core/io/database/mongodb.py, src/orion/core/io/database/pickleddb.py, src/orion/core/utils/tests.py, src/orion/storage/legacy.py, tests/unittests/core/mongodb_test.py, tests/unittests/core/test_ephemeraldb.py, tests/unittests/core/test_pickleddb.py, tests/unittests/storage/test_legacy.py
Why:
The index metadata.user will be removed in v0.1.6, but this will cause
issues with experiments from previous versions since the index will
still be present.
How:
Use the same API as mongodb for both, with a simplified
`index_information` where the output is simply a dictionay mapping
{name}_{order} to {True, False} whether the index is unique or not.
Why:
Version 0.1.6 will remove the index metadata.user, so we need to make
sure we remove it from the db as well.
=> Fix backward compatibility for metadata.user index

docs/src/user/algorithms.rst, src/orion/algo/asha.py, src/orion/algo/space.py, src/orion/core/worker/__init__.py, src/orion/core/worker/producer.py, tests/conftest.py, tests/functional/algos/asha_config.yaml, tests/functional/algos/black_box.py, tests/functional/algos/random_config.yaml, tests/functional/algos/test_algos.py, tests/functional/branching/test_branching.py, tests/unittests/algo/test_asha.py, tests/unittests/algo/test_space.py, tests/unittests/core/test_producer.py
Why:
There was no documentation on the fact that ASHA requires the
SubParallelStrategy. There was also no documentation at all about the
parallel strategies...
Why:
If an algo is done, but only *realizes* during an update in `produce`,
then the algo will opt out indefinitely and the process will crash. This
should be handled and leave gracefully.
How:
Check for algo.is_done at each loop iteration in `produce` and stop if
True.
Why:
The EVC is using the default_value to build adapters. Also this default
value can be used as a fall-back if the algorithms does not support
multi-fidelity optimization. This is handy is we want to try different
algorithms with the same experiment configuration.
Why:
The termination condition was wrong and would stop when the penultimate
rung was filled, making …
=> Fix ASHA termination condition and branching with fidelity()

src/orion/core/cli/info.py, src/orion/storage/base.py, tests/functional/commands/conftest.py, tests/functional/commands/test_info_command.py, tests/unittests/core/cli/test_info.py
Why:
When something is different in the environment, the experiment may
branch since we are not using a `View` in `info`. We should rather use a
view but for now they don't have access to instantiated space and
algorithms which are required by `info`.
How:
Use a view and reconfigure it to instantiate the space and algo. This is
not done by default in `View` because they crash if the users scripts in
the experiment are not present on the current FS. At least now this only
happens in `info`, which was already the case anyway since we were not
using a `View`.
=> Avoid branching in `info`

docs/src/index.rst, docs/src/user/script.rst, docs/src/user/searchspace.rst, src/orion/core/worker/consumer.py, tests/functional/demo/black_box.py, tests/functional/demo/black_box_w_config.py, tests/functional/demo/black_box_w_config_other.py, tests/functional/demo/test_demo.py
Note: Documentation missing.
Why:
The user may require the experiment name, experiment id, trial id or
working-dir through another mean than commandline arguments. The
environment variables seams a legitimate way to communicate this
information.
=> Add env-vars to consumer

src/orion/core/io/experiment_builder.py, src/orion/core/utils/exceptions.py, src/orion/core/worker/experiment.py, tests/unittests/core/worker/test_experiment.py
Why:
If 2 experiments are created simultaneously and both lead to the same
version increment, one may be created as version=1 and then fail to
resolve the name conflict because version=2 has been registered
meanwhile. This should be resolved by raising an error signaling a race
condition to force the experiment builder to restart the experiment
creation from scratch, as it is done to handle race conditions for
experiment registration during experiment creation.
How:
During conflict detection in experiment.configure, if the
ExperimentNameConflict is not resolved and version number was not
requested (experiment should take last version), then we raise a
RaceCondition error to signal the race condition.
=> Handle race conditions during version increment

src/orion/core/evc/conflicts.py, src/orion/core/io/cmdline_parser.py, src/orion/core/io/convert.py, src/orion/core/io/experiment_builder.py, src/orion/core/io/orion_cmdline_parser.py, src/orion/core/utils/tests.py, src/orion/core/worker/consumer.py, src/orion/core/worker/experiment.py, tests/conftest.py, tests/functional/commands/conftest.py, tests/functional/demo/test_demo.py, tests/functional/gradient_descent_algo/setup.py, tests/unittests/core/conftest.py, tests/unittests/core/evc/test_conflicts.py, tests/unittests/core/io/test_cmdline_parser.py, tests/unittests/core/io/test_converters.py, tests/unittests/core/io/test_orion_cmdline_parser.py, tests/unittests/core/sample_config_template.txt, tests/unittests/core/test_branch_config.py, tests/unittests/core/worker/test_consumer.py, tests/unittests/core/worker/test_experiment.py
Why:
We need the parser state to be able to resume the experiment without the
configuration file. It is also convenient for monitoring scripts where
the configuration file often isn't available locally.
Finally, this is a step in direction of support for python API, as the
prior dict in metadata[prior] will serve as the config used to create
the space instead of metadata[user_args]. This will uniformize how
cmdline and python APIs are handled.
How:
OrionCmdlineParser, CmdlineParser and all Converters now have
`get_state_dict()` and `set_state_dict()` methods so that we can save
the state in metadata and restore the parser without the cmdline and config file.
=> Save parser state in DB

src/orion/core/worker/transformer.py, tests/unittests/core/test_transformer.py
Why:
The vectorized function of Enumerate could not be `deepcopy`ed making it
unusable because of naive algorithm's that requires copying the original
algo.
How:
Overwrite `__deepcopy__` the rebuild the Enumerate object instead of
copying it.
=> Fix deepcopy of Enumerate transform

src/orion/core/io/database/ephemeraldb.py, tests/unittests/core/test_ephemeraldb.py
Why:
The expected behavior when a selection is done on a non-existing field
is that it will be returned with the value None. Similarly, if an index
is created for a non-existing field it should be considered as being
equal to None.
How:
In the selection, verify if there was any match for a selection key, if
not, assign it None. For the non-existing index, document[key] should
return None when document does not contain key.
=> Handle non-existing fields in EphemeralDB

docs/src/install/core.rst
Why:
It was not mentioned anywhere that we only support Linux and OSX.
=> Add mention of windows in install doc

.travis.yml, src/orion/core/cli/test_db.py, src/orion/core/io/database/ephemeraldb.py, src/orion/core/utils/backward.py, src/orion/core/utils/tests.py, src/orion/core/worker/experiment.py, tests/conftest.py, tests/functional/backward_compatibility/black_box.py, tests/functional/backward_compatibility/random.yaml, tests/functional/backward_compatibility/test_versions.py, tests/functional/commands/conftest.py, tests/functional/demo/test_demo.py, tests/unittests/core/conftest.py, tests/unittests/core/evc/test_conflicts.py, tests/unittests/core/test_branch_config.py, tests/unittests/core/worker/test_consumer.py, tests/unittests/core/worker/test_experiment.py, tox.ini
During release v0.1.6 two bugs have been introduced that made it
impossible to reuse data created with v0.1.5 with the PickledDB
backend. This kind of problems should be automatically detected when
making changes in the develop branch.
For each previous versions (starting with 0.1.3), a db is created using
the old version (0.1.3, 0.1.4, etc) and then all commands are tested in
the current version (test-db, list, status, hunt, etc). The outputs are
not tested thouroughly, this should be covered by the unit-tests. The
tests here only verify that commands run successfully. All tests are run
for each db backend.
This should fail in the PickledDB tests until #284 is merged in `develop`.
=> Add functional tests for backward-compatibility

docs/src/code/core/cli.rst, docs/src/code/core/cli/db.rst, docs/src/code/core/cli/db/setup.rst, docs/src/code/core/cli/db/test.rst, docs/src/code/core/cli/test_db.rst, docs/src/install/database.rst, src/orion/core/cli/db/__init__.py, src/orion/core/cli/db/setup.py, src/orion/core/cli/db/test.py, src/orion/core/cli/db_main.py, src/orion/core/cli/setup.py, src/orion/core/cli/test_db.py, tests/functional/backward_compatibility/test_versions.py, tests/functional/commands/test_setup_command.py
Why:
We will shortly add more database related commands such as `remove` and
`upgrade`. They should all be grouped within `orion db`.
=> Turn test-db into db test

docs/src/install/database.rst, src/orion/core/cli/db/upgrade.py, src/orion/core/io/database/__init__.py, src/orion/core/io/database/ephemeraldb.py, src/orion/core/io/experiment_builder.py, src/orion/core/utils/backward.py, src/orion/storage/base.py, src/orion/storage/legacy.py, tests/conftest.py, tests/functional/backward_compatibility/test_versions.py, tests/unittests/storage/test_legacy.py, tests/unittests/storage/test_storage.py
Why:
There is breaking changes in the DB scheme (mostly importantly in the
unique indexes definition). To fix this, we will provide a command to
upgrade the db scheme explicitely (not implicitly during execution like
we were first attempting). This will avoid breaking DBs and simplify the
handling of backward compatibility in the db.
How:
- Add checks during DB creation to fail fast if the db is outdated and
incompatible with current version
- Add command `orion db upgrade` to fix the indexes and add missing
fields (version, priors)
=> Add `orion db upgrade` command

src/orion/core/worker/experiment.py, tests/unittests/core/worker/test_experiment.py
Why:
When handling the configured experiment, we expect the adapter to be
instiantiated even if it does nothing (empty CompositeAdapter).
=> Instantiate adapter even if empty

src/orion/algo/space.py, src/orion/core/cli/db/upgrade.py, src/orion/core/evc/conflicts.py, src/orion/core/io/experiment_builder.py, src/orion/core/utils/backward.py, src/orion/core/worker/experiment.py, tests/conftest.py, tests/functional/commands/conftest.py, tests/unittests/algo/test_space.py, tests/unittests/core/conftest.py, tests/unittests/core/evc/test_conflicts.py, tests/unittests/core/io/test_experiment_builder.py, tests/unittests/core/io/test_space_builder.py, tests/unittests/core/test_branch_config.py, tests/unittests/core/test_ephemeraldb.py, tests/unittests/core/test_pickleddb.py, tests/unittests/core/worker/test_consumer.py, tests/unittests/core/worker/test_experiment.py
Note:
Depends on #297 
Why:
The space definition used to be implicitely stored in
metadata[user_args] when the only API was the commandline one. With the
python API it becomes much more convenient to store the space definition
in the DB explicitely as it is how the user will provide it.
How:
If using the commandline API, parse the user_args, build the space and
save the configuration of the space in DB. If using the python API,
simply save the space in DB directly.
=> Add Space definition in DB

src/orion/core/io/database/ephemeraldb.py, tests/unittests/core/test_ephemeraldb.py, tests/unittests/core/test_pickleddb.py
Why:
When remove documents, the corresponding indexes would not be deleted,
making impossible to insert new documents with these values.
=> Fix EphemeralDB index update after document deletion

src/orion/core/cli/info.py, src/orion/core/evc/adapters.py, src/orion/core/io/orion_cmdline_parser.py, src/orion/core/utils/format_trials.py, src/orion/core/worker/trial.py, src/orion/storage/track.py, tests/functional/algos/test_algos.py, tests/functional/branching/test_branching.py, tests/functional/demo/test_demo.py, tests/unittests/core/cli/test_info.py, tests/unittests/core/evc/test_adapters.py, tests/unittests/core/evc/test_experiment_tree.py, tests/unittests/core/test_trial.py, tests/unittests/core/test_utils_format.py, tests/unittests/core/worker/test_experiment.py
Why:
The list structure is very cumbersome and does not match the interface
provided to users to define space. The params structure as a dict is
more coherent. The ordering of the params is important however for the
hashing of the trial, hence we keep the list as a private attribute and
only expose a dict of {name:value} of the trials, which is more
convenient for the user interface.
=> Expose trial.params as a dict

docs/src/user/algorithms.rst
Why:
The format 1e-10 is not a valid format for scientific numbers in yaml
and will be converted to string.
=> Fix doc for bayesopt's alpha

src/orion/client/experiment.py, src/orion/core/io/space_builder.py, src/orion/core/worker/trial.py, tests/unittests/client/test_experiment_client.py, tests/unittests/core/io/test_experiment_builder.py, tests/unittests/core/io/test_space_builder.py
Why:
The python API is convenient to use with a hierarchical space structure
if there is many dimensions, just as we would do in configuration files.
Note that this does not support conditional dimensions, each dimension
is independent, but the space is represented in a hierarchical
structure. See contributed unit-tests for an example.
=> Add support for space hierarchical structure

src/orion/core/utils/format_trials.py, tests/unittests/client/test_experiment_client.py, tests/unittests/core/conftest.py, tests/unittests/core/test_utils_format.py
Why:
The formating was not flattening the params when turning them to tuple
for algo.observe.
=> Fix formatting of trial with subdict params

src/orion/algo/asha.py, tests/unittests/algo/test_asha.py
Why:
If the scale is too small and there is many rungs, then some fidelity
levels will have the same values. We can catch this and increase the
wrong ones to avoid duplicates.
=> Support small fidelity scales for ASHA

src/orion/storage/legacy.py, src/orion/storage/track.py
Storage factory implicitly import backends when importing orion/storage/base which cause a cyclic dependency
Solution is to break the cycle by importing Trial lazily in the backends
```
Traceback (most recent call last):
File "/home/setepenre/work/olympus/olympus/report/dashboard.py", line 13, in <module>
from orion.storage.base import Storage
File "/home/setepenre/work/orion/src/orion/storage/base.py", line 213, in <module>
class Storage(BaseStorageProtocol, metaclass=SingletonFactory):
File "/home/setepenre/work/orion/src/orion/core/utils/__init__.py", line 57, in __init__
super(SingletonType, cls).__init__(name, bases, dictionary)
File "/home/setepenre/work/orion/src/orion/core/utils/__init__.py", line 112, in __init__
entry_point.load()
File …
```
=> make trial import lazy to avoid cyclic dependencies

src/orion/core/io/experiment_builder.py, tests/functional/branching/test_branching.py, tests/unittests/core/io/test_experiment_builder.py
Why:
When the algo is passed again, it resulted in dropping the algo
configuration altogether. This lead to a reversal to RandomSearch and thus
the experiment would have a different algo and branch.
How:
Overwrite config[algo] with the user's defined algorithm since it has
precedence over db anyway.
=> Algo redefinition should not drop algo config

docs/src/examples/pytorch_cifar.rst
Why:
A few commands were not formatted and a sed command was shown without any explanation which is susceptible to deteriorate the readability and comprehension of the example, threatening the engagement of potential and current users.
How:
Formatted the commands similarly to the others in the example and added a minimum descriptions.
=> Formatted commands and added a command description

docs/src/examples/pytorch_cifar.rst, docs/src/user/pytorch.rst
Cloning via HTTPS is the default option presented by GitHub and doesn't require extra configuration from the user.
=> Clone via HTTPS instead of SSH

ROADMAP.md
This PR refreshes the roadmap for the v0.1.8 release.
The major changes are:
- Removed the v0.1.8 section since it will be release at the time
- Moved v0.2 to Short-Term
- Added TPE and HyperBand to v0.2
- Moved visualization to Mid-Term
- Added the new feature of using the EVC as a knowledge base to optimize trials
=> Updated the roadmap for v0.1.8

docs/src/code/client.rst, docs/src/code/client/cli.rst, docs/src/examples/pytorch_a2c_ppo.rst, docs/src/examples/pytorch_cifar.rst, docs/src/user/api.rst, docs/src/user/pytorch.rst, src/orion/algo/base.py, src/orion/client/__init__.py, src/orion/client/cli.py, src/orion/core/__init__.py, src/orion/core/cli/base.py, src/orion/core/utils/exceptions.py, src/orion/core/worker/__init__.py, src/orion/core/worker/consumer.py, src/orion/storage/legacy.py, tests/functional/client/black_box.py, tests/functional/client/orion_config.yaml, tests/functional/client/test_cli_client.py, tests/unittests/client/test_client.py, tests/unittests/storage/test_legacy.py
Some users need a way to signal an interruption from within the script.
While KeyboardInterrupt in the shell where orion's worker is running
would catch the signal properly and interrupt the trial, raising
KeyboardInterrupt from within the script would only lead to a completed
script with error code > 0, hence the trial would be set to broken.
This commit adds a new helper function for this, `interrupt_trial`,
which terminates the process with a special code defined by Oríon, so
that the worker can detect that this is not a broken trial, but
an interrupted one.
Additional helper functions are added to simplify usage of Oríon:
`report_objective` and `report_bad_trials`.
=> Add more helper functions for cmdline client

.travis.yml, conda/conda_build.sh, setup.py, tests/functional/gradient_descent_algo/setup.py, tox.ini
Why:
Python 3.8 was released a few days ago.
For python 3.5, it lack of builtin ordered dictionary is growing
cumbersome and likely not worth the hassle.
=> Drop python3.5 support and add python3.8

src/orion/client/__init__.py, src/orion/core/cli/base.py, src/orion/core/io/experiment_builder.py, src/orion/core/utils/exceptions.py, tests/functional/branching/test_branching.py, tests/unittests/client/test_client.py, tests/unittests/core/io/test_experiment_builder.py
Why:
Users are confused when there is an error because of branching events.
Most of branching events are handled automatically, but when commandline
arguments are different for each workers or user scripts writes in code
repo there is a race condition between the version increments and it
fails.
How:
Write a clear message to explain what are the typical causes for these
issues and give hints on how to solve it.
=> Add comprehensive error message for branching err

src/orion/core/worker/producer.py, src/orion/core/worker/trial.py, tests/unittests/core/test_trial.py, tests/unittests/core/worker/test_producer.py
Why:
It seams the EVC tree was not used inside the producer... Making the EVC
somewhat useless beside traceability between experiments.
Why:
The check against duplicates relies on the trial id which is a hash
based on the experiment id and the params. Problem is, the trial of
different experiment in the EVC have different experiment id, thus
different hash for the same parameters. To avoid duplicates between two
experiments in the EVC, we need to rely on a check before the
registration of the trial. This can only work of there is no parallel
workers on the 2 different experiment at the same time. This should be
the case since experiments are typically run sequentially, and
parallelism occurs within a single experiment.
How:
Keep track of hash of trials based on params only (including …
=> Use EVC tree trials in producer

tox.ini
Why:
Best practice is to use **tox** as the facade to launch all the coverage, packaging and testing taks. It is often necessary to test specific, localized tests or modules during development using the command `$ tox -e devel -- path/to/your/tests`.
However, the latter command isn't used by the CI which rely on a regular `tox` call which will internally call **tox** on different environments. The developer can emulate this behaviour using `$ tox -e py36` to test the Python 3.6 environment. Unfortunately, this will run the **entire** test suite which can take a significant portion of the developer time.
This PR proposes to add the option for the developer to run specific tests instead of the entire environment test suite, enabling him to quickly verify that his changes will not break in …
=> Enabling localized testing via tox

docs/src/examples/cluster.rst, docs/src/examples/pytorch_a2c_ppo.rst, docs/src/examples/pytorch_cifar.rst, docs/src/user/cli/info.rst, docs/src/user/evc.rst, docs/src/user/pytorch.rst
PR #333 adds support to entry points, removing the requirement to make
scripts executable. This commit adapts to doc to this new feature.
=> Changed documentation to support non-executable python files

docs/src/index.rst, docs/src/user/config.rst, src/orion/client/__init__.py, src/orion/client/experiment.py, src/orion/core/__init__.py, src/orion/core/cli/base.py, src/orion/core/cli/evc.py, src/orion/core/cli/hunt.py, src/orion/core/evc/conflicts.py, src/orion/core/io/config.py, src/orion/core/io/experiment_branch_builder.py, src/orion/core/io/experiment_builder.py, src/orion/core/io/resolve_config.py, src/orion/core/worker/__init__.py, src/orion/core/worker/consumer.py, src/orion/core/worker/experiment.py, tests/conftest.py, tests/functional/demo/test_demo.py, tests/unittests/core/io/orion_config.yaml, tests/unittests/core/io/test_config.py, tests/unittests/core/io/test_experiment_builder.py, tests/unittests/core/io/test_resolve_config.py, tox.ini
Why:
So far some arguments were supported either in global, local or cmdline,
sometimes in the same format, sometimes in different format. This
was horribly confusing for users.
How:
Force the local config to use the same format as global config by using
the latter as a reference point while parsing local config. The cmdline
arguments are processed and turned into a dictionary following the
structure of the global config.
Why:
The help message for options is scattered and duplicated all over the code.
We should use the configuration as a common ground, where help messages
are globally defined. Also, there is many modifications coming to make
global, local and commandline options more coherent, which will require
many deprecation. Adding the deprecation inside the configuration makes
it …
=> Make global, local and cmdline args coherent

CONTRIBUTING.md, MANIFEST.in, README.rst, docs/src/developer/overview.rst, docs/src/index.rst
Adds the contribution guidelines for the project in the recommended CONTRIBUTING.md open-source standard. The goal of this file is to provide a short and sweet introduction to contributing to the project. 
The developer documentation will contain the main information about setting up the development environment, testing, documenting, and packaging.
I drew inspirations from the following sources:
- https://mozillascience.github.io/working-open-workshop/contributing/
- https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md
- https://github.com/atom/atom/blob/master/CONTRIBUTING.md
- https://github.com/mila-iqia/cookiecutter-pypackage/blob/master/CONTRIBUTING.rst
=> Contribution guidelines

src/orion/algo/base.py, src/orion/algo/random.py, tests/unittests/algo/test_random.py
Why:
The filtering of duplicates in RandomSearch is a lot more efficient than
relying on the database with DuplicateKeyErrors. There will still be
race conditions leading to this error, but filtering upfront in
RandomSearch reduces significantly the number of registration failures
and lead to better workload balance between the workers. Without this
fix, some workers end up always updating their algo and trying to sample
the next point but loose all race conditions.
How:
Use _trial_info to filter out duplicates while sampling points...
=> Avoid duplicates in RandomSearch

src/orion/algo/base.py, src/orion/core/worker/experiment.py, src/orion/core/worker/producer.py, tests/conftest.py, tests/unittests/algo/test_base.py, tests/unittests/core/worker/test_experiment.py, tests/unittests/core/worker/test_producer.py
Why:
We need to be able to discern when experiment is completed and no more
trials should be executed, and when algorithm is completed and no more
trials should be created. With current experiment.is_done, we sample
more than `max_trials`. Adding `max_trials` to termination criterion of
algo makes it possible for the algo to flag when it should not sample
new points, but still experiment.is_done is False because there is
pending trials.
How:
Add max_trials to algo in `Producer`. This is somewhat hacky but
`max_trials` is tightly integrated to `Experiment` so moving it to
algorithms would be complicated. Maybe something we should consider
doing later on.
In experiment.is_done, it now return True if number of completed trials
is greater than or equal to `max_trials`, or if …
=> Add max_trials to algorithm.is_done

src/orion/core/io/database/__init__.py, src/orion/core/io/database/mongodb.py, src/orion/core/io/database/pickleddb.py, tests/unittests/core/test_pickleddb.py
Why:
When there are timeouts, the errors are not handled and
python leaves with scary stack-traces in terminal for users.
There is typical issues causing timeouts in PickledDB, the error message
should explain these to the users so they learn what to do to fix it.
Note:
They timeouts never occurred for MongoDB during the stress test and it
is not clear what message should be provided to users, given there is no
obvious root problems as of now. So I leave this as empty reraise, and
do not test...
=> Handle timeout in DBs (PickledDB in particular)

docs/src/code/algo.rst, docs/src/code/algo/hyperband.rst, docs/src/user/algorithms.rst, src/orion/algo/hyperband.py, src/orion/core/worker/__init__.py, tests/functional/algos/hyperband.yaml, tests/unittests/algo/test_hyperband.py
This PR include below fixes for Hyerband:
- Compute budgets does not output the same table as the original paper
**Fix**: Besides the fix, also add a debug log to show the budget table like this:
- Duplicate points in a single hyperband execution will cause some points been tried but won't be able to register into the correct budget since we choose bracket one time based on fidelity. 
**Fix**: Won't allow repeated points in a single hyperband execution. And if the search space is too small to fill the first rungs of all brackets, hyperband won't be able to promote and experiment only run the points of the first rungs and exit.
- Support to run duplicate points in different hyperband execution only if the later one get bigger fidelity compared with previous execution.
- When multiple …
=> hyperband fixes

docs/src/user/library/evc_results.rst
Why:
There is a broken link in the monitoring section when referencing the EVC. https://trello.com/c/HWp2LH8J
How:
I replaced the broken external link with a valid internal link. This way, if the linked document is moved, the build system will throw an error.
=> Fix broken-link in monitoring

CONTRIBUTING.md, docs/src/developer/ci.rst, docs/src/developer/documenting.rst, docs/src/developer/installing.rst, docs/src/developer/overview.rst, docs/src/developer/standards.rst, docs/src/developer/testing.rst, docs/src/index.rst, docs/src/install/core.rst, docs/src/install/database.rst
In this pull request, we refresh, update and reorganize the documentation for developers. The objective is to have a simple, easy to read and exhaustive place where developers come to guide them to developing for Oríon.
Please note, this documentation doesn't have the same role as CONTRIBUTING.md. Its role is to give developers all the information they need build and modify Oríon by themselves (and then do a PR :)).
=> Update developer documentation

docs/src/plugins/base.rst
These changes update the landing page for plugin development.
- The title is changed to reflect the true nature of the page.
- Add link to the cookiecutter template.
- Integrate the link to gradient descent algorithm plugin as an example of cookiecutter template.
=> Add link to cookiecutter template

LICENSE, docs/src/code/storage.rst, docs/src/code/storage/base.rst, docs/src/code/storage/legacy.rst, docs/src/code/storage/track.rst, docs/src/index.rst, docs/src/user/api.rst, docs/src/user/storage.rst, src/orion/client/__init__.py, src/orion/core/__init__.py, src/orion/core/io/experiment_builder.py, src/orion/core/worker/experiment.py, src/orion/core/worker/strategy.py, src/orion/storage/base.py, src/orion/storage/legacy.py, src/orion/storage/track.py, tests/unittests/core/test_strategy.py, tests/unittests/storage/test_legacy.py, tests/unittests/storage/test_storage.py
Why:
Database corruption occurs when there is Timeouts in PickledDB. The objective is saved but status is not set to completed.
How:
We catch non-completed trials with objective and log a warning with a pointer to documentation to manually fix corrupted trials.
Note:
Also add substantial documentation on storage which was required to document what the user can do to fix the database corruption.
=> Handle trials with corrupted status 

README.rst
Why:
The current DOI (10.5281/zenodo.3478593) represent Oríon v0.1.7. When a new version will be released, this DOI will change and will need to be updated. Often, researchers do not want to cite a specific version but rather the software as a whole. The advantage is that there is only one way to reference the software instead of having one citation for each version which is tedious and undermines the referencing of Oríon and its discoverability among peers.
How:
Replace the references to the DOI for the current version with a DOI that represents all versions. [Learn more](https://help.zenodo.org/#versioning).
=> Cite latest version of Oríon by default

docs/src/developer/installing.rst
Currently, _master_ is the default branch. It is not a problem per say except that developers need to switch branch when they make a PR.
However, switching to _develop_ would bring a lot of advantages and no drawbacks.
- New users arriving on the page will see an active project
- Nothing changes for users except that they now have to specify to clone on master when installing via Git. This installation method is not recommended (prefer using PyPI) and represent a small portion of installs from advanced users.
- Developers cloning the projects automatically work on the right branch (_develop_)
The only modification related to the project is to remove the specification to clone the develop branch for new developers.
When this PR is accepted, we can switch the default branch on the project's …
=> Changing the default branch to develop

CONTRIBUTING.md, README.rst, docs/src/developer/documenting.rst, docs/src/developer/release.rst
I updated the **latest** and **stable** channels in https://readthedocs.org/ to respectively build from the branch develop and master. When linking our Sphinx documentation to the README, we can encounter problems when making a release where the documentation pointing to latest is not updated to stable, sending visitors to 404 error pages.
This content of this  PR defines how such links are to be used on the README and how to migrate them during a release to integrate them to the legacy release documentation.
=> Documentation guidelines for internal links on the README

.flake8, .pylintrc, MANIFEST.in, dev-requirements.txt, docs/src/developer/release.rst, tox.ini
These changes are refreshing `tox.ini` to increase the maintainability of the project and the good practices, and updating the linting packages.
- `tox.ini` is now sorted by environment first. The misc package configs are moved at the end.
- The `flake8` configuration is moved to a standalone `.flake8` file  to improve linting compatibility with IDEs, and unclutter `tox.ini`.
- `dev-requirement.txt` now contains only the package `tox`. Since it's the only package required for developing. The other dependencies were duplicates of the environments dependencies specified in `tox.ini`.
- Versions for linters `pylint`, `flake8`, and `doc8` have been updated to their latest version*.
- New rules introduced by the update to the linters have been **disabled for now** **.
- Relaxed `basepython` …
=> Update TOX configuration

src/orion/core/worker/trial.py, src/orion/storage/legacy.py, src/orion/storage/track.py, tests/unittests/client/test_experiment_client.py, tests/unittests/storage/test_storage.py
With the user interface it is possible that users try to set trials with
invalid status. We should verify the validity of the status before
potentially corrupting the database.
Add validity checks in storage.set_trial_status to make sure status is valid.
=> Validate provided status before updating trial

docs/src/developer/standards.rst
Add the documentation describing the label categories and convention we use on Github.
Existing labels are formally grouped in a handful of extensible categories. *Priority* and *Status* categories are introduced.
=> Add doc about label categories

src/orion/core/io/resolve_config.py
Fix #390
Instead of printing the `repr()`, the suggested change is now passed through `yaml.dump()`
=> Show proper yaml syntax in resolve_config deprecation warnings containing None

src/orion/client/experiment.py, tests/unittests/client/test_experiment_client.py
Exceptions during python execution leads to end of program, executing
`atexit` which marks reserved trials as broken. The special case of
KeyboardInterruption however should be handled differently, with the
trials set to interrupted instead.
During `atexit` execution, the `sys.exc_info()` is looked up to decide
whether the trials should be set at `interrupted` or `broken`.
- [ x] I added corresponding tests for bug fixes and new features. If possible, the tests fail without the changes
- [x ] All new and existing tests are passing (`$ tox -e py38`; replace `38` by your Python version if necessary)
- [x ] I have updated the relevant documentation related to my changes
- [x ] I have read the [CONTRIBUTING](https://github.com/Epistimio/orion/blob/develop/CONTRIBUTING.md) doc
- [x ] My …
=> Catch keyboard interrupt in Python API

src/orion/algo/asha.py, tests/unittests/algo/test_asha.py
It was currently rounded taking the floor value. This lead to budgets
which were below the actual fidelity dimension.
Fixed #393 & #392
=> Round ASHA budget properly

docs/src/install/core.rst
Updates the compatibility status of Oríon on Windows.
Oríon can be used on Windows 10 using the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about).
=> Document Windows compatibility

docs/src/plugins/install.rst, docs/src/user/algorithms.rst, docs/src/user/script.rst, src/orion/core/io/resolve_config.py
The user may (it happened, see #395 ) simply transfer the producer config
to experiment section, in which case it will ignored.
Verify if producer is defined in experiment section of config and handle it.
Update docs according to new config format
=> Handle producer config in experiment section

README.rst, docs/src/user/script.rst
Adds a line to promote the ability of Oríon to work with any language and support for any configuration file.
=> Promote Oríon's agnosticity

src/orion/core/cli/__init__.py, src/orion/core/cli/base.py, src/orion/core/cli/hunt.py, src/orion/core/cli/init_only.py, src/orion/core/cli/insert.py, src/orion/core/io/experiment_builder.py, src/orion/core/utils/exceptions.py, tests/functional/commands/test_db_commands.py, tests/functional/commands/test_hunt_command.py, tests/functional/commands/test_info_command.py, tests/functional/commands/test_init_only_command.py, tests/functional/commands/test_insert_command.py, tests/functional/demo/test_demo.py
Why:
Orion was crashing with a confusing error message.
How:
Detect if no command is defined, if so print help message and exit.
=> Print help when calling `orion` alone

src/orion/core/io/database/mongodb.py
Using hasattr(db, 'count_document') will always be True, but will return
a collection if the method does not exist (new in version 3.7).
Test if attribute is a collection, if it is then used old count().
=> Fix mongodb count for v < 3.7

src/orion/core/cli/hunt.py, src/orion/core/io/experiment_builder.py, tests/functional/commands/test_hunt_command.py, tests/unittests/core/io/test_experiment_builder.py
When a user execute `orion hunt` without any prior the application raises an unrelated exception without any explanation to the user.
The number of priors is verified during the parsing and inform the user that the command requires at least one prior.
=> Raise exception when no prior is provided

docs/src/user/api.rst
The documentation showcases three different levels of API: sequential, service, and framework. However, sequential and service APIs are accessible from the same module and have a similar usage making it confusing for the user. Additionally, these two APIs are fundamentally the same, except sequential is a in-memory optimization helper method, thus making its sovereignty as its own module questionable.
We merge the documentation of the two APIs. There is no need to merge the APIs' source code since this separation exists only in the doc.
=> Merging Sequential and Service API

CODE_OF_CONDUCT.md, MANIFEST.in
Added Contributor Covenant (https://www.contributor-covenant.org/) as the code of conduct for Oríon.
Currently, the point of contact is to create a new issue. It would be better if the point of contact was an email instead, dedicated to the project if possible.
=> Code of conduct

docs/src/developer/release.rst, tests/functional/backward_compatibility/python_api.py, tests/functional/backward_compatibility/test_versions.py
Why:
Versions < 0.1.6 where available on pypi's orion.core which was deleted to avoid confusion.
=> Drop support for orion < 0.1.6

tests/unittests/algo/test_space.py
The test `test_no_prior` is using the operation `in` to test for string equality which is generally ambiguous semantically and wrong in this case since we compare two string for equality.
The pull request replaces `in` by `==`.
=> Fix test using 'in' to assert equality

docs/src/install/database.rst, docs/src/user/cli/status.rst, docs/src/user/storage.rst, src/orion/core/cli/db/rm.py, src/orion/core/io/experiment_builder.py, src/orion/storage/base.py, src/orion/storage/legacy.py, src/orion/storage/track.py, tests/functional/commands/test_db_rm.py, tests/functional/commands/test_info_command.py, tests/functional/commands/test_insert_command.py, tests/unittests/core/io/test_experiment_builder.py, tests/unittests/storage/test_storage.py
Add a command to delete experiments based on name and version number, as well as trials based on status.
The format of the command is ```orion db rm <exp name> [--version VERSION] [--status STATUS]```.
Executing ```orion db rm <exp name>``` will remove the experiment, its children and all corresponding trials.
Specifying the ```--status``` will result in deleting the trials only.
Methods `delete_experiment` and `delete_trials` are added to the storage interface and implemented for the Legacy backend. For now the Track backend does not support it.
To avoid coupling the experiment builder, the EVC and the storagte, the method `delete_experiment` removes the given experiment only, not the children. The implementation of the hierarchical deletion is done in the CLI module …
=> Add command `orion db rm`

src/orion/core/io/experiment_builder.py, src/orion/core/worker/consumer.py, tests/unittests/core/worker/test_consumer.py
Why:
We test the code version at beginning of experiment but it could change
during an execution, leading to trials ran with different code versions.
How:
Validate before the execution of the trial that code version did not
change. If so, raise BranchingEvent().
Note:
There may be race conditions between the validation and the execution of the trial.
The only solution for this would be to test the code version at
beginning of trial execution but that would require reimplementation for
all languages of users' scripts...
=> Quit if code changed between two trials execution

docs/src/user/storage.rst, src/orion/core/cli/base.py, src/orion/core/cli/db/rm.py, src/orion/core/cli/db/set.py, src/orion/core/cli/db/setup.py, src/orion/core/cli/status.py, src/orion/core/utils/terminal.py, src/orion/storage/base.py, src/orion/storage/legacy.py, src/orion/storage/track.py, tests/functional/commands/conftest.py, tests/functional/commands/test_db_set.py, tests/unittests/storage/test_storage.py
Users need a way to change values of some fields of the trials, namely
the status.
A command orion db set is added. It supports query for a single
attribute (ex: status=completed) and update for single attributes as
well (ex: status=interrupted). So far only `status` and `id` are
supported for queries and `status` for updates. These are likely to be
sufficient for the majority of use cases.
As for orion db rm, the updates are recursive in children experiments.
Depends on #425
=> Add command `orion db set`

src/orion/core/worker/experiment.py, tests/unittests/core/worker/test_experiment.py
`is_broken` is a property defined in `Experiment`. Since it's a read-only property with no side effects. It should be included in the authorized attributes for instances of `ExperimentView`.
=> Enable `is_broken` for ExperimentView

src/orion/core/utils/format_terminal.py, src/orion/core/worker/experiment.py, tests/unittests/core/cli/test_info.py
When using the CLI command `orion info`, it will now print the working_dir variable.
E.g.,
Config
======
pool size: 1
max trials: 2
working dir: orion_working_dir
Just added working_dir to the list of variables printed under "Config"
- [x ] I added corresponding tests for bug fixes and new features. If possible, the tests fail without the changes
- [x ] All new and existing tests are passing (`$ tox -e py38`; replace `38` by your Python version if necessary)
- [x ] I have updated the relevant documentation related to my changes
- [ x] My commits messages follow [this format](https://chris.beams.io/posts/git-commit/)
- [x ] My code follows the style guidelines (`$ tox -e lint`)
=> added info about working_dir when using orion info CLI

src/orion/core/worker/trial.py, tests/unittests/core/test_trial.py
Trial supports results of type 'objective', 'constraint', 'gradient', and 'statistic'; it's not possible to fetch more than one result. For the results of type 'gradient' and 'objective' it's acceptable since multi-objective optimization is not yet supported. However, multiple results of type 'constraint' and 'statistic' can already be supported.
This pull request adds properties to fetch the results of type 'constraint' and 'statistic'.
=> Specialized properties for Trials

src/orion/serving/plots_resources.py, src/orion/serving/webapi.py, tests/functional/serving/test_plots_resource.py
This is the last foundational pull request for the REST API. It adds the `/plots` endpoint and serves regret plots as the first kind of plot available.
For more information, refer to #423.
=> REST plotting endpoint with regret plots

docs/src/code/core/cli.rst, src/orion/core/cli/base.py, src/orion/core/cli/db/rm.py, src/orion/core/cli/db/set.py, src/orion/core/cli/db/setup.py, src/orion/core/cli/db/test.py, src/orion/core/cli/db/upgrade.py, src/orion/core/cli/db_main.py, src/orion/core/cli/hunt.py, src/orion/core/cli/info.py, src/orion/core/cli/init_only.py, src/orion/core/cli/insert.py, src/orion/core/cli/list.py, src/orion/core/cli/serve.py, src/orion/core/cli/setup.py, src/orion/core/cli/status.py, src/orion/core/cli/test_db.py
The command line subcommands do not have descriptions that make it hard to use Oríon without looking at the documentation.
This PR fixes a few documentation problems and adds a short and long description for each subcommand, indicating what are their purposes.
=> CLI documentation improvements

src/orion/core/utils/format_terminal.py, tests/unittests/core/cli/test_info.py
Why:
The information whether an experiment is completed is important and
should be part of what `info` provides.
=> Add `completed` field to `info` cmd

src/orion/core/io/experiment_builder.py
Remove the outdated root parameter documentation `branch_from` from `experiment_builder.build()`.
➡️ https://trello.com/c/BAoRdVCK
=> Remove outdated `branch_from` parameter documentation in `experiment_builder.build()`

conda/meta.yaml, docs/src/conf.py, setup.py
Unsorted extensions and modules list makes it hard to maintain and can cause merge conflicts when merged to develop.
This pull request sorts alphabetically:
- The list of Sphinx extensions
- The list of orion modules in setup.py
- The list of orion modules in conda/meta.yaml
=> Sort modules and extensions alphabetically

src/orion/client/__init__.py, tests/conftest.py, tests/unittests/client/test_client.py
`orion.client` is the public-facing API to work with experiments. However, there is currently no intuitive way to retrieve an experiment for the only viewing past results. Currently, the options are to either use `orion.client.create_experiment()` which is semantically opposed to what the user wants to do or use `orion.core.io.experiment_builder.build_view()` which is located in internal modules.
This PR adds an intuitive method to retrieve existing experiments through `orion.client.get_experiment`. An instance of `orion.core.worker.experiment.ExperimentView` is returned to ensure a read-only experience.
=> Add orion.client.get_experiment()

src/orion/core/cli/base.py, src/orion/core/utils/exceptions.py, src/orion/core/worker/consumer.py, tests/functional/demo/test_demo.py
Why:
A common error is to try running orion on a script that is not
executable. Orion currently prints the whole stack trace to user which
is unclear and somehow scary for users. We should give a clear error
message instead.
How:
Catch PermissionError in Popen and then raise a custom
InexecutableUserScript with a clear error message.
Add InexecutableUserScript to the list of errors that are catched by the
base argparse to print user friendly error messages.
=> Print user friendly err msg if script inexecutable

src/orion/core/worker/transformer.py, tests/unittests/core/test_transformer.py
Why:
When the categorical dimension is transformed to one-hot, the interval
returned should be in the space of the one-hot otherwise the algorithm
requesting a real space cannot handle the categories.
How:
Add an interval method to OneHot Transformer.
TransformerDimension will look for an interval method, otherwise use the
default interval of original dimension.
Note that CompositeTransformer push the interval() method recursively if
necessary, so that a one-hot encoding that is part of a composite
transformer can still provide its interval().
=> Return onehot interval instead of categorical

docs/src/user/script.rst
The correct name for this orion working directoy variable seems to be ORION_WORKING_DIR.
In the docs instead there is ORION_WORKING_DIRECTORY.
=> changed variable name in docs to reflect the correct name

src/orion/core/worker/transformer.py, tests/unittests/core/test_transformer.py
Why:
When the number of categories is only 2, we rely on (0, 1) encoding with
a threshold of 0.5. When number of categories is greater than 2, we rely
on a one-hot encoding. Previous implementation of interval was only
returning the one-hot encoding version, creating a mismatch with shape
when number of categories is 2.
=> Adjust OneHotEncoding interval shape

docs/src/user/algorithms.rst
Why:
The algorithm configuration was not under the `experiment` section of the configuration. The StubParallelStrategy, which is necessary for HyperBand (EvolutionaryES inherits from it), was not included in the config.
=> Fix config of EvolutionaryES

src/orion/core/io/experiment_builder.py, src/orion/core/io/orion_cmdline_parser.py, src/orion/core/utils/backward.py, src/orion/core/utils/flatten.py, tests/functional/commands/conftest.py, tests/functional/commands/test_info_command.py, tests/functional/commands/test_list_command.py, tests/functional/commands/test_status_command.py, tests/functional/demo/test_demo.py, tests/unittests/core/io/test_experiment_builder.py, tests/unittests/core/io/test_orion_cmdline_parser.py, tests/unittests/core/utils/test_flatten.py
If the user pass script configs to experiments, the monitoring tools will fail to fetch the corresponding experiments if the script configs cannot be found. The information necessary for monitoring is already available in the database, so we can ignore the files if they cannot be found.
- Extend orion cmdline parser to handle command lines with non existing configuration files
- Fix bug in flatten() to handle dictionaries containing double references.
- Add force_update option in backward.populate_space so that build_view can avoid loading the config files.
=> Support non existing user script conf files 

src/orion/storage/legacy.py, src/orion/storage/track.py, tests/unittests/core/worker/test_experiment.py, tests/unittests/storage/test_storage.py
Why:
The fetch of lost trials should look for trials with heartbeat older
than x * heartbeat (with x > 1) otherwise we will often catch trials
that are being run (ex: heartbeat late by a microsecond). It used to be
2 * heartbeat. For some reason it was now 1 * heartbeat...
How:
Set it back to 5 * heartbeat to be sure, and rework the unittest to
verify that trials lost but with heartbeat that are not 5 * heartbeat
late yet are not fetched.
=> Fix fetch_lost_trials

.github/workflows/build.yml
The release triggered 3 times the workflow. We should only catch one of
the events.
Also added support for manual trigger of the workflow.
=> Only publish on release:published

src/orion/client/__init__.py, src/orion/client/experiment.py, src/orion/core/io/experiment_builder.py, src/orion/core/utils/backward.py, src/orion/core/utils/format_terminal.py, src/orion/core/worker/experiment.py, src/orion/serving/responses.py, tests/functional/demo/orion_config.yaml, tests/functional/demo/orion_config_other.yaml, tests/functional/demo/orion_config_random.yaml, tests/functional/demo/test_demo.py, tests/functional/serving/test_experiments_resource.py, tests/unittests/client/test_client.py, tests/unittests/client/test_experiment_client.py, tests/unittests/core/cli/test_info.py, tests/unittests/core/io/orion_config.yaml, tests/unittests/core/io/test_experiment_builder.py, tests/unittests/core/io/test_resolve_config.py, tests/unittests/core/worker/test_experiment.py
The experiment was using `worker.max_broken` but max_broken for the
experiment is also configurable and should be handled differently.
=> Add max_broken in exp configuration

docs/src/user/config.rst, src/orion/core/__init__.py, src/orion/core/cli/evc.py, src/orion/core/io/config.py, src/orion/core/io/experiment_builder.py, src/orion/core/io/resolve_config.py, src/orion/core/utils/backward.py, src/orion/core/worker/experiment.py, src/orion/core/worker/strategy.py, src/orion/storage/base.py, tests/conftest.py, tests/functional/configuration/conftest.py, tests/functional/configuration/test_all_options.py, tests/functional/demo/test_demo.py, tests/unittests/client/test_client.py, tests/unittests/core/cli/test_evc.py, tests/unittests/core/io/test_config.py, tests/unittests/core/io/test_resolve_config.py
[fixes #466, fixes #469, fixes #470 ]
The configuration of Oríon is complex due to its support of hierarchical customization (global, env vars, local, cmd args). This PR adds extensive tests verifying configuration for each groups (storage, experiment, worker, evc) at each hierarchical level (global, env vars, db, local, cmd args). It also verifies that configuration at upper levels properly overrides values defined at lower levels (ex: local overrides global).
=> Adds extensive functional testing for configuration

src/orion/core/evc/conflicts.py, src/orion/core/io/experiment_builder.py, tests/functional/branching/test_branching.py
[fixes #471 ]
Why:
When removing a hyperparameter from the search space, the merge of
configuration would bring it back from previous version. We should not
merge the search space, only override it if redefined.
=> Handle rm/add properly in EVC

src/orion/core/io/database/ephemeraldb.py, tests/unittests/core/test_ephemeraldb.py
Why:
The $set operator in mongodb is meant to replace values, not to update
subdict.
How:
If $set is used to update dict, iterate on fields to $set and replace
with flattened version.
=> Override fields with set, not update

src/orion/algo/space.py, src/orion/core/io/space_builder.py, src/orion/core/worker/transformer.py, tests/functional/algos/test_algos.py, tests/unittests/algo/test_asha.py, tests/unittests/algo/test_hyperband.py, tests/unittests/algo/test_space.py, tests/unittests/core/test_transformer.py
There was two errors.
1. The integer bounds are inclusive, but the cardinality was computed as if
the upper bound was exclusive.
2. The shape affects cardinality exponentially, it would be
(cardinality of one item) ** prod(shape), not (cardinality of one item) * prod(shape).
Why:
There is a mismatch between the inclusive bound of Integer and
the underlying distribution (which is real) where high is in theory exclusive
but in practice inclusive due to limited precision and rounding.
We cannot use numpy.round() to fix this because otherwise the probability
is changed for lowest and highest possible numbers. For instance a
uniform distribution (0, 10) would have a probability of 0.5 * (1/10)
for 0 instead of (1/10).
How:
In the cast method, rescale the point from (low, high) to
(low, high + …
=> Fix cardinality and integer cast

src/orion/algo/space.py, src/orion/algo/tpe.py, src/orion/core/cli/insert.py, src/orion/core/utils/backward.py, src/orion/core/worker/primary_algo.py, src/orion/core/worker/transformer.py, tests/unittests/core/test_transformer.py
[fixes #368, fixes #175]
Many algorithms and analysis requires a flattened version of the space
where any dimension with shape > 1 is converted into prod(shape)
individual dimensions.
The space transformation builder is refactored to support new format of
requirements. Instead of a confusing list of requirements
(see #368), the algorithm may
define 3 types of requirements,
- the dimension type (real, integer, numerical or None (any)),
- the dimension distribution (linear, or None (any)) and
- the dimension shape (flattened, or None (any))
The ReshapedDimension unpacks a dimension of `shape` into `prod(shape)`
dimensions of shape 1, with name `{name}[index]`.
=> Add ReshapedSpace and Linearize transformer

src/orion/algo/base.py, src/orion/core/utils/backward.py, tests/unittests/core/utils/test_backward.py
Why:
The requires field was still in BaseAlgorithm leading the backward
compatibility function to always look at .requires instead of the other
fields.
=> Fix algorithm requirements backward

conda/meta.yaml, setup.py, src/orion/core/io/database/pickleddb.py, tests/unittests/core/test_pickleddb.py
[fixes #434]
Why:
When using PickledDB with distributed file systems that do not support
global lock, the database can become corrupted and lead to critical
losses of data.
How:
Look at mount point of the database file and verify if it supports
global lock, otherwise use a SoftFileLock.
=> Use SoftFileLock if FS doesn't support global lock

.pylintrc, src/orion/core/cli/base.py, src/orion/core/io/experiment_builder.py, src/orion/core/utils/backward.py, src/orion/core/worker/__init__.py, src/orion/core/worker/experiment.py, src/orion/core/worker/producer.py
[Fixes #516]
Experiment branching in particular was difficult to debug based on logs.
This also adds timestamps at the beginning of logs to help debug race conditions.
=> Add debugging verbosity

src/orion/plotting/backend_plotly.py, tests/unittests/plotting/test_plotly_backend.py
[Fixes #518]
Why:
The LPI requires the objective. If we don't filter the non-completed trials, the
computation fails.
How:
Filter out non-completed trials in the plotting function. The analysis
function assumes trials with objectives, otherwise it would required
passing data frames including status.
=> Ignore non-completed trials when computing LPI

src/orion/algo/asha.py, src/orion/algo/hyperband.py, tests/functional/algos/test_algos.py, tests/unittests/algo/test_asha.py, tests/unittests/algo/test_hyperband.py
[Fixes #488]
Why:
Hyperband and ASHA would fail if they are passed trials that they did
not sample.
How:
Save sampled ids in algos and only observe points that were previously
sampled, otherwise ignore. This way we could still salvages points from
EVC if the current algo sample points that are in EVC (with same
fidelity), otherwise it ignores the points.
=> Support EVC in all algos

src/orion/core/cli/insert.py, src/orion/core/io/experiment_builder.py, src/orion/core/io/orion_cmdline_parser.py, src/orion/core/io/resolve_config.py, tests/conftest.py, tests/functional/branching/test_branching.py, tests/functional/commands/experiment.yaml, tests/functional/commands/test_info_command.py, tests/functional/commands/test_insert_command.py, tests/functional/configuration/test_all_options.py, tests/unittests/core/conftest.py, tests/unittests/core/evc/test_conflicts.py, tests/unittests/core/io/test_experiment_builder.py, tests/unittests/core/test_branch_config.py, tests/unittests/core/worker/test_experiment.py
Why:
The code version was not infered properly when `orion hunt` is called
with only experiment name, not passing the user script cmdline.
How:
Re-infer code version based on merge of old metadata and new metadata.
=> Detect code change when no CMDLINE passed

docs/src/user/config.rst, docs/src/user/evc.rst, src/orion/client/__init__.py, src/orion/core/__init__.py, src/orion/core/cli/evc.py, src/orion/core/evc/adapters.py, src/orion/core/evc/conflicts.py, src/orion/core/io/experiment_branch_builder.py, src/orion/core/io/experiment_builder.py, src/orion/core/io/interactive_commands/branching_prompt.py, src/orion/plotting/backend_plotly.py, src/orion/serving/webapi.py, tests/functional/branching/test_branching.py, tests/functional/commands/experiment.yaml, tests/functional/commands/test_insert_command.py, tests/functional/configuration/test_all_options.py, tests/functional/serving/test_plots_resource.py, tests/unittests/client/test_client.py, tests/unittests/client/test_experiment_client.py, tests/unittests/core/conftest.py, tests/unittests/core/evc/test_adapters.py, tests/unittests/core/evc/test_conflicts.py, tests/unittests/core/evc/test_resolutions.py, tests/unittests/core/io/interactive_commands/test_branching_prompt.py, tests/unittests/core/io/test_experiment_builder.py, tests/unittests/core/io/test_resolve_config.py, tests/unittests/core/test_branch_config.py, tests/unittests/plotting/test_plotly_backend.py, tests/unittests/storage/test_storage.py
[Fixes #487]
Why:
Changing the version of Oríon could impact the behavior of the HPO,
therefore we should branch to avoid corrupting results.
How:
Add Conflict, Resolution and Adapter to detect and handle changes of
orion version.
=> Branch if Oríon version changes

docs/src/user/library/evc_results.rst, docs/src/user/library/results.rst, docs/src/user/storage.rst, src/orion/client/__init__.py, src/orion/client/experiment.py, src/orion/core/cli/db/rm.py, src/orion/core/cli/db/set.py, src/orion/core/cli/info.py, src/orion/core/cli/insert.py, src/orion/core/cli/list.py, src/orion/core/cli/status.py, src/orion/core/evc/experiment.py, src/orion/core/io/experiment_builder.py, src/orion/core/utils/exceptions.py, src/orion/core/worker/experiment.py, src/orion/plotting/base.py, src/orion/serving/parameters.py, tests/functional/branching/test_branching.py, tests/functional/commands/test_db_set.py, tests/unittests/client/test_client.py, tests/unittests/core/evc/test_experiment_tree.py, tests/unittests/core/io/test_experiment_builder.py, tests/unittests/core/worker/test_experiment.py, tests/unittests/plotting/test_plotly_backend.py
[Fixes #517, #519, #531]
The experiment view is useful to query the database and make plots, but
sometimes we want to add new trials or make modifications to trials
(like status) without executing the experiments. Making such edit should
not require building the experiment with checks for branching, as there
is no intention in executing trials. There should be
read/write/execution rights instead of just providing a view.
Read can:
Make any calls that only require reading the DB. No writes on DB
Read/Write can:
Make any calls that read or write the DB as long as it is not updating
trial results. Also the producer should not be accessible in Read/Write
mode, the algorithm should not be executed in an unchecked environment.
Read/Write/Exec can:
Do everything.
Remove ExperimentView and add …
=> Add Read/Write/Execution modes for Experiment

.readthedocs.yml, MANIFEST.in, setup.py
Readthedocs is failing since release 0.24 of scikit-learn. This is due to a missing wheel for manylinux1 as explained [here](https://github.com/scikit-learn/scikit-learn/issues/19233).
Setting readthedocs configuration to run installation with pip instead of installing from source with `setup.py` solves the issue.
=> Fix readthedocs build

src/orion/analysis/lpi_utils.py, src/orion/plotting/backend_plotly.py, src/orion/plotting/base.py, src/orion/testing/plotting.py, tests/unittests/analysis/test_lpi.py, tests/unittests/plotting/test_plot_accessor.py
Why:
The LPI metric is not deterministic and depend on the initial state of
the regression model used. We make multiple runs with different
``random_state`` and compute the average LPI with its standard
deviation.
=> Add error bar to LPI

src/orion/plotting/backend_plotly.py, src/orion/plotting/base.py, tests/unittests/plotting/test_plot_accessor.py, tests/unittests/plotting/test_plotly_backend.py
[Fixes #534]
The behavior is confusing when user wants to plot in some exp-{v>1}
and only part of the trials show up. Until now the plots would never
include trials from parent experiments. This commit makes it
configurable and True by default.
=>  Make plots use trials in EVC by default

tox.ini
Fix #569.  Now codecov should report coverage on all files within src/ and not report anything about the tests.
There may be some lingering reports about `tests/functional/backward_compatibility/test_version.py`, because this was the file that had coverage previously, but those should disappear with time.
tox now installs the package in development mode, to allow coverage to keep track of files.
=> Fix for coverage issue

src/orion/core/worker/experiment.py, src/orion/storage/base.py, src/orion/storage/legacy.py, src/orion/storage/track.py, tests/unittests/storage/test_storage.py
This adds a `where` parameter to the `fetch_trials` method of all Storage interfaces (legacy and tracks). This is useful behavior that can be used to simplify some tests which currently use `_fetch_trials`, and it improves the consistency of the interface wrt the `update_trials` and `delete_trials` methods which already take a `where` parameter.
=> Add where parameter to Storage.fetch_trials

src/orion/core/cli/db/setup.py, src/orion/core/io/database/__init__.py, src/orion/core/io/database/ephemeraldb.py, src/orion/core/io/database/mongodb.py, src/orion/core/io/database/pickleddb.py, src/orion/core/utils/terminal.py, tests/functional/commands/test_setup_command.py
Update command line `orion db setup` to ask for arguments depending of storage backend typed in first question.
To automate retrieval of storage backend arguments, a class method `get_arguments()` is added to base class `AbstractDB`.
Fixes #573
=> Make command `orion db setup` ask for right arguments based on storage backend.

src/orion/client/experiment.py, src/orion/storage/base.py, src/orion/storage/legacy.py, src/orion/storage/track.py, tests/unittests/client/test_experiment_client.py, tests/unittests/storage/test_storage.py
Why:
Some trial status updates require the trial to have a specific status
(like releasing the trial reservation). In such case, `set_trial_status`
should not verify that status in database in current trial.status, but
rather that the trial status should be a precise one.
How:
Add argument `was` which will override current trial status if given.
=> Handle cases when trial.status is not reserved anymore locally.

src/orion/client/experiment.py, src/orion/core/worker/trial.py, tests/unittests/client/test_experiment_client.py
There are hangs in the tests when `release(trial)` is not invoked on a reserved trial (#583).
After discussion, it is agreed that the `atexit()` handling strategy should be abandoned in favour of turning `Trial` into a context manager, usable with the Python `with`-statement. We begin doing so here.
=> [WIP] Add context-manager-enabled Trial subclass.

src/orion/algo/tpe.py, src/orion/testing/algo.py, tests/unittests/algo/test_tpe.py
Why:
Some algorithms may have issues with different type of values. For
instance TPE was failing to sample ``None`` values because it was
recognized as `GMM failed to sample` inside TPE.
=> Test different type of categorical dims

src/orion/algo/tpe.py, tests/unittests/algo/test_tpe.py
fix issue https://github.com/Epistimio/orion/issues/600
Update tpe real and int sampler to be consistent with the default space dimension from cardinality.
- real
uniform(0, 5) => before the fix, tpe samples from [0,5), after the fix, tpe samples [0,5]
- integer
uniform(0, 5, discrete=True) => before the fix, tpe samples from [0,5), after the fix, tpe samples [0,5]
=> fix tpe space cardinality

src/orion/benchmark/__init__.py, src/orion/plotting/backend_plotly.py, tests/unittests/benchmark/test_benchmark.py
Fix:
1) banchmark experiment parallel execution parameter is inconsistent with `experimentclient.workon`
2) Rankings plot show wrong and different result compared with regrets
=> fix benchmark ranking and regret visualization

docs/src/user/algorithms.rst, src/orion/algo/asha.py, src/orion/algo/evolution_es.py, src/orion/algo/hyperband.py, src/orion/algo/random.py
To simplify documentation of algorithm plugins, they have been moved to
separate docs, with only pointers in core documentation.
The algorithms class documentation is also reused to avoid rewriting the
documentation of the arguments in sphinx.
=> Change algo documentation

src/orion/core/evc/conflicts.py, tests/functional/branching/test_branching.py
[Fixes #553]
Why:
Suppose we want to branch from a parent running from a different
computer, or for which we lost the execution script. The branching
should not fail because script is missing, we do not need it because we
wont execute trials from the parent anyway.
How:
Use allow_non_existing_files=True when building the cmdline parser to
compare cmdlines of experiments.
=> Allow branching when parent script isn't available

src/orion/core/cli/db/upgrade.py, tests/functional/backward_compatibility/test_versions.py
[Fixes #554]
Why:
The space upgrade relies on local files if the experiment's search space
is defined in a configuration file. Parsing these file during the DB
upgrade can break the DB because all experiments may not be executed on
the same file system and thus some configuration files may not be
present. The space should only be upgraded when the user attempts
running an experiment, in which case the configuration file is available.
The space does not need to be upgraded during DB upgrade anyway, because
experiment built is backward compatible with experiments lacking an
explicit space definition in DB (relying on cmdargs and config file to
define space at run-time).
How:
Remove space upgrade from db upgrade script.
=> Remove space upgrade from DB upgrade

src/orion/core/__init__.py, src/orion/core/cli/evc.py, src/orion/core/cli/hunt.py, src/orion/core/evc/conflicts.py, src/orion/core/io/experiment_branch_builder.py, src/orion/core/io/experiment_builder.py, src/orion/core/io/resolve_config.py, src/orion/core/worker/consumer.py, tests/functional/algos/test_algos.py, tests/functional/branching/test_branching.py, tests/functional/commands/conftest.py, tests/functional/commands/test_insert_command.py, tests/functional/configuration/test_all_options.py, tests/functional/serving/test_trials_resource.py, tests/unittests/client/test_client.py, tests/unittests/core/io/interactive_commands/test_branching_prompt.py, tests/unittests/core/io/test_experiment_builder.py, tests/unittests/core/io/test_resolve_config.py, tests/unittests/core/worker/test_consumer.py, tests/unittests/core/worker/test_producer.py, tests/unittests/plotting/test_plotly_backend.py
[Fixes #547]
The EVC is a constant source of confusion for users. It should be
disabled by default with warning messages when different versions of
experiments are used. Users who wants using advanced features of the EVC
would still be able to use it by enabling it.
Making it false by default is a breaking change and may cause issues to
user currently using the EVC. Based on discussion with users there does
not seem to have much usage of the EVC so far so this breaking change
should be relatively harmless. Avoiding further confusion by making it
disabled by default is worth the breaking change.
=> Add enable option for EVC, with default = false

setup.py, src/orion/algo/space.py, src/orion/client/__init__.py, src/orion/core/utils/__init__.py, src/orion/core/worker/transformer.py, src/orion/executor/single_backend.py, tests/functional/algos/test_algos.py, tests/unittests/algo/test_space.py, tests/unittests/core/test_transformer.py, tests/unittests/core/utils/test_utils.py
[Fixes #633]
Why:
With loguniform the number of possible values is limited if precision is
used. Cardinality computation should account for this otherwise
algorithms may get stuck in suggest(). It happened to a user with a
prior loguniform(1e-4, 1e-2, precision=2). This gives only 181 possible
values.
How:
If real dimension has precision and prior loguniform, then compute
cardinality.
There is a problem with transformed space however. A linearized
dimension for instance would attempt to compute the cardinality with the
linearized bounds. What matters is the smallest cardinality between the
transformed space and the original space. The only case where
cardinality is smaller in transformed space is when real values are
discretized. Therefore, we only compute cardinality of transformed …
=> Compute cardinality for loguniform with precision 

src/orion/core/io/experiment_builder.py, tests/unittests/core/io/test_experiment_builder.py
A warning about conflicts was always printed when building an
experiment. There should be no warning if there are no difference.
=> Warn only if diffs exists during exp build

src/orion/benchmark/__init__.py, src/orion/benchmark/benchmark_client.py, src/orion/client/__init__.py, src/orion/client/experiment.py, tests/unittests/benchmark/test_benchmark_client.py, tests/unittests/client/test_experiment_client.py
Instead of global executor configure, support to set executor at benchmark level.
fix issue: https://github.com/Epistimio/orion/issues/624
Adding parameter executor of type `orion.executor.base.Executor` to run the benchmark experiments.
```
def get_or_create_benchmark(
name, algorithms=None, targets=None, storage=None, executor=None, debug=False
):
```
=> Support to configure executor for benchmark

src/orion/algo/tpe.py, tests/unittests/algo/test_tpe.py
[Solves #647]
Why:
The GMM for real values could not sample efficiently in narrow spaces.
It would often lead to RuntimeError because the number of attempts
allowed would be exhausted. We could increase the default number of
attempts allowed but that would increase the computational cost for any
space, even those easy to sample.
How:
Use numpy array to avoid playing with a list. It is more efficient.
Also, increase the number of attempts as needed until it reaches a max
value of attempts. This way easy samples do not take more time while
difficult ones are allowed more.
=> Fix TPE sampling in narrow spaces

src/orion/core/evc/conflicts.py, tests/functional/branching/test_branching.py
[Fixes #636]
Why:
The option `user_script_config` is part of the worker configuration, not
the EVC. As such, this option is not part of `branching` group of option
and does not find its way to the Conflict objects of the EVC. The value
of user_script_config is already available anyway inside the
experiment configuration, so there is no need to pass it. Furthermore, it may
differ from past experiments to the new one, and both experiments should be handled
based on their respective `user_script_config`, not the new one. For
these reasons, it is better to use the information available in the
experiment configurations.
=> Use user_script_config from parser in EVC

src/orion/core/io/experiment_builder.py
[Fixes #533]
Why:
When trying to branch from an experiment that already has a child with
the same name, Oríon will crash with a RaceCondition error. The problem
is that this issue and a real race-condition are indiscernible as they
lead to the same state. The only thing we can do is clarify the error
message and warn that this error can also be caused by branching from a
parent experiment that already has a child with the same name.
Note:
This issue only arises if the user specifies the version of the parent
experiment, otherwise the EVC will use the child or branch from the
child without any issue.
=> Clear error message for dup branching error

src/orion/algo/space.py, src/orion/core/evc/adapters.py, tests/unittests/algo/test_space.py, tests/unittests/core/conftest.py, tests/unittests/core/evc/test_adapters.py, tests/unittests/core/evc/test_resolutions.py
[Fixes #535]
Why:
The shape of categorical dimensions was not included in
`get_prior_string`, causing the lost of the shape during branching.
How:
Add the shape to `get_prior_string` of Categorical dimensions and add
tests to catch this issue.
Also add tests for Conflict and Resolutions of priors with different
shape.
The adaptor for a change of prior does not raise an issue anymore when
shapes are different and rather logs a warning. The trials are all
ignored is this case.
=> Fix shape argument in categorical dims

src/orion/algo/tpe.py, src/orion/core/worker/transformer.py, tests/unittests/algo/test_tpe.py, tests/unittests/core/test_transformer.py
[Fixes #552]
Why:
A log integer dimension would be casted to real, linearized, then casted
back to integer. This reduces dramatically the number of possible values
that can be sampled as many exp(int(log(x))) will result in the same
integer for many different values of x. An algorithm that needs
linearization should be able to handle real space or otherwise state a
requirement for integers. This should be handled separately and
quantization of linearized log integer should not be applied by default.
Note:
Due to the use of floor instead of rounding in Quantize, the values of
int(exp(log(x))) would still clash for close values of x. Using rounding
instead solves the issue. Rounding may be problematic however for
algorithms that require integer type, as the rounding may cast real
integers …
=> Support linearize log integer properly

src/orion/algo/tpe.py, tests/functional/algos/test_algos.py, tests/unittests/algo/test_tpe.py
[Fixes #679]
If TPE keep sampling points already suggested, the suggest loop will run
infinitely. This adds a `max_retry` to limit the number of iterations on
the loop.
=> Avoid inf-loop in TPE.suggest

src/orion/algo/asha.py, src/orion/algo/base.py, src/orion/algo/evolution_es.py, src/orion/algo/hyperband.py, src/orion/testing/algo.py, tests/unittests/algo/test_asha.py, tests/unittests/algo/test_gridsearch.py, tests/unittests/algo/test_hyperband.py
Why:
Currently only one promotion can be done for each suggest. This means
with pool-size greater than 1 ASHA would always end up suggesting many
new trials and only do 1 promotion at a time.
=> Support batched promotions in ASHA 

docs/src/user/config.rst, src/orion/algo/hyperband.py, src/orion/client/__init__.py, src/orion/client/experiment.py, src/orion/core/__init__.py, src/orion/core/cli/hunt.py, src/orion/core/utils/exceptions.py, src/orion/core/worker/producer.py, tests/functional/configuration/test_all_options.py, tests/unittests/algo/test_asha.py, tests/unittests/algo/test_hyperband.py, tests/unittests/client/test_experiment_client.py, tests/unittests/core/io/test_resolve_config.py, tests/unittests/core/worker/test_producer.py
Why:
We had two levels of patience when reserving a trial. There was the
customizable `max_idle_time` used in producer.produce() to limit the
time spend trying to generate new trials, and there was `_max_depth` in
`reserve_trial` limiting the number of times a reservation would be
attempted and producer.produce would be called. This lead to misleading
error messages. For instance, with many workers it happened that a
worker would always be unable to reserve a trial because each time it
executed producer.produce() all other workers would reserve the trials
before the current worker had time to reserve one. In such scenario the
error message would be that the algorithm was unable to sample new point
and is waiting for trials to complete. It is not true. We should state
the number of trials …
=> Improve resiliency of trial reservation

src/orion/algo/asha.py, src/orion/algo/hyperband.py, tests/unittests/algo/test_asha.py, tests/unittests/algo/test_hyperband.py
Why:
The sorting of trials during promotion was not only looking at
objectives, but also at trials. Problem is, trials are not comparable.
This bug was not detected because during tests trials always have a
different objective, hence the comparisons would always stop at the
objective when comparing the tuples (objective, trial).
How:
Add tests with identical objectives, and use objective only for sorting.
=> Fix ASHA for identical objectives

conda/meta.yaml, setup.py, src/orion/benchmark/__init__.py, src/orion/client/experiment.py, src/orion/core/utils/format_terminal.py, src/orion/core/worker/experiment.py, src/orion/serving/experiments_resource.py, src/orion/serving/responses.py, tests/functional/example/test_scikit_learn.py, tests/unittests/core/cli/test_info.py, tests/unittests/core/worker/test_experiment.py
The custom section of the docstring was causing issues when compiling
the documentation. Also returning a generic dict was not ideal, creating
a dataclass instead provides better documentation and interface for the
users.
=> Replace exp's stat dict by a dataclass

src/orion/core/cli/base.py, tests/functional/commands/test_verbose_messages.py
Prints Orion version if verbose level is debug.
```
% orion -vv
```
Implements changes requested in issue #735.
Quite straitforward. 
n/a
=> Print version on debug verbosity level

setup.py, src/orion/serving/webapi.py
Hi, @bouthilx ! I suggest this pull request to make orion server support CORS (cross-origin resource sharing) requests.
Currently, Orion will reject any API call made from a server located in a different address than himself. For example, if orion server is at `http://myorionserver.com`, and I make an API call from a local server (`http://localhost`), then API call won't work because servers addresses are different.
This PR adds and uses Python package `falcon-cors`. I guess an orion server should be public, so `falcon-cors` currently makes server accepts requests from any other server. But, if necessary, we could later restrict allowed requests to a specific list of addresses.
I need this PR to make `orion-dashbord` API calls work correctly.
=> Add falcon-cors requirement to make orion server accept CORS requests

src/orion/algo/pbt/exploit.py
=> Escape the escape

src/orion/executor/dask_backend.py, src/orion/executor/multiprocess_backend.py, src/orion/executor/single_backend.py, tests/unittests/executor/test_executor.py
=> Fix multiprocess del guard

src/orion/core/io/cmdline_parser.py, src/orion/core/io/orion_cmdline_parser.py, tests/unittests/core/io/test_cmdline_parser.py, tests/unittests/core/io/test_orion_cmdline_parser.py
Signed-off-by: Fabrice Normandin <fabrice.normandin@gmail.com>
Fixes #769 
~~- [ ] I have updated the relevant documentation related to my changes~~
=> Fix parsing of hps with "." in name from commandline

setup.py, src/orion/serving/webapi.py
Reverts Epistimio/orion#778
This is to solve conda packaging for release v0.2.2.
=> Revert "Add falcon-cors requirement to make orion server accept CORS requests"

conda/ci_build.sh, conda/meta.yaml, setup.py, src/orion/core/__init__.py, src/orion/core/io/resolve_config.py, src/orion/serving/webapi.py, tests/functional/serving/conftest.py, tests/functional/serving/test_root.py, tests/unittests/core/io/test_resolve_config.py
Hi @bouthilx ! This is a pull request to wrap all changes related to CORS handling for Orion Web API. I will close other related pull requests so that we can focus only on this one.
This PR adds option `frontends_uri` to list allowed frontend addresses and add `falcon-cors` dependencies for PYPI (using original package) and conda (using conda package I built from PYPI package and uploaded on my anaconda repo)
- Re-add changes reverted from https://github.com/Epistimio/orion/pull/792
- Add changes from https://github.com/bouthilx/orion/pull/4
- Changes should fix https://github.com/Epistimio/orion/issues/793
- Changes should resolve issue from https://github.com/Epistimio/orion/pull/780
- Add changes from https://github.com/Epistimio/orion/pull/782
- Changes should fix …
=> Add config option `frontends_uri` to specify allowed frontend addresses for Orion Web API

src/orion/algo/base.py, src/orion/testing/algo.py
When the trial is broken it should be considered as such by the
algorithm, it is not pending anymore.
algo.has_observed(broken_trial) should return True.
=> Test algo can handle broken trials

src/orion/algo/base.py, tests/unittests/algo/test_base.py
Fixes #860 (just the `__init__` part)
=> Detect _param_names from __init__ signature

src/orion/testing/algo.py, tests/unittests/algo/pbt/test_pbt.py, tests/unittests/algo/test_asha.py, tests/unittests/algo/test_evolution_es.py, tests/unittests/algo/test_gridsearch.py, tests/unittests/algo/test_hyperband.py, tests/unittests/algo/test_random.py, tests/unittests/algo/test_tpe.py
- Test phases can be directly set using the `phases` class attribute instead of having to call `TestMyAlgo.set_phases`.
- Also adds a `TestPhase` NamedTuple that gives a better description of each item, since the "raw" tuples are a little bit unintuitive IMO.
=> Simplify setting test phases in Test Classes

CITATION.bib
Based on the docs here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
This should generate a "Cite this repository" tab on the right of the GitHub page of Orion: [Like this](https://docs.github.com/assets/cb-230711/images/help/repository/citation-link.png)
=> Add CITATION.bib to make it easier to cite Orion

src/orion/core/worker/primary_algo.py, tests/functional/algos/test_algos.py, tests/unittests/core/test_primary_algo.py
Fixes #882 (at least I think it does)
=> Add number of suggest() attempts in Algo wrapper

src/orion/plotting/backend_plotly.py
The plotting backend functions fetch a trial of the experiment to infer the objective. For a freshly branched experiment that doesn't have trials yet, the trial list is empty. This results in an IndexError when the functions try to access the first element of the `fetch_trials_by_status()` calls [here](https://github.com/Epistimio/orion/blob/e13326d6453ed15c98e3f2ff7989c5ad1a4b7ccd/src/orion/plotting/backend_plotly.py#L127) and [here](https://github.com/Epistimio/orion/blob/e13326d6453ed15c98e3f2ff7989c5ad1a4b7ccd/src/orion/plotting/backend_plotly.py#L521). 
This PR changes the `fetch_trials_by_status` calls to copy the plotting functions' `with_evc_tree` arguments to (optionally) fetch trials from prior versions of the experiment if the `with_evc_tree` flag is set to `True`.
Optional: …
=> Fix IndexError for freshly branched exp

src/orion/testing/algo.py, tests/unittests/algo/long/nevergrad/integration_test.py, tests/unittests/algo/pbt/test_pbt.py, tests/unittests/algo/test_random.py
- Missing `from __future__ import annotations` at the top of `integration_test.py`
- Remove the Generic base for the test class, which prevented tests from being  collected in python 3.7
=> Hotfix for nevergrad tests

.pre-commit-config.yaml, MANIFEST.in, docs/src/developer/ci.rst, tox.ini
Devs can optionally turn on pre-commit locally using:
```console
$ pip install pre-commit
$ pre-commit install
```
Then, the following actions are performed on the diff before it is committed locally:
- black: Reformat the code using black
- codespell: Check for spelling mistakes
- flake8: check for various code quality issues
- isort: sort imports
- pyupgrade: Remove outdated python syntax stuff from the code (e.g. super(thing, self), etc)
- autoflake: Remove unused imports
If any of the above hooks fail, the commit is interrupted, the differences get added as modifications, and the user can add them before the commit goes through.
It's really simple and convenient.
The only thing that I'm not 100% sure about is codespell, which I think might generate a bunch of false positives. Even …
=> Add .pre-commit-config.yaml for local setup

dashboard/src/src/utils/queryServer.js
Hi @bouthilx . This is a fix to make Dashboard tests pass. I hope it will work.
Increase timeout for axios to make API calls.
=> [dashboard] Increase Axios timeout

src/orion/algo/space.py, src/orion/core/io/database/__init__.py, src/orion/core/worker/experiment.py, src/orion/core/worker/transformer.py, src/orion/core/worker/trial.py
Fix some formatting in the docs to avoid missing sections and weirdly formatted arguments list.
1. Using custom section is bad because sphinx skips them and doesn't show anything in the rendered docs.
2. Typos in the section names are bad for the same reason.
3. `arg : type` renders as `argtype`
`arg: type` renders as `arg: type`
As a general comment, the docstrings seems to use at least two different markup standards (I have seen numpydoc and reST) often in the same file.
It would be good to standardize on one style and try to enforce it and it may help with odd formatting that may be caused by the doc parser getting confused by the different styles.
=> Fix some documentation formatting

src/orion/algo/base.py
Fixes a bug when inferring the param names (configuration keys) for algorithms that inherit from `typing.Generic`, in python 3.7.
In python 3.7, the Generic class has a metaclass (GenericMeta or something similar), and inspect.signature(type(self)) would give
the signature of the metaclass's `__call__` method, instead of the signature of the __init__ of the class.
Also fixed a bug whereby it would include "self" and "args" from *args into the param names.
This wasn't causing issues because we check if `self` has an attribute with the given name before including it in the configuration.
Signed-off-by: Fabrice Normandin <fabrice.normandin@gmail.com>
=> Fix bug with algo param_names

dashboard/src/src/__tests__/benchmark.test.js, dashboard/src/src/__tests__/experiments.databasePage.test.js, dashboard/src/src/experiments/content/DatabasePage/DatabasePage.js, dashboard/src/src/experiments/content/DatabasePage/TrialTable.js, dashboard/src/src/style.css
Hi @bouthilx ! This is a PR to display experiment trials in database page.
- Display trials for selected experiment in database page.
- Trials are displayed in a table.
- Trial parameters and statistics are displayed as a small table inside the trials table.
- A unit test is added and succeeds on my computer, tough there is not currently CI testing for dashboard.
=> [dashboard] Display trials for selected experiment in Database page

dashboard/src/src/__tests__/flattenObject.test.js, dashboard/src/src/experiments/content/DatabasePage/DatabasePage.js, dashboard/src/src/utils/flattenObject.js
Hi @bouthilx , this is a PR to display parameters in separated columns with flattened parameter names.
Still don't know what to do with testing. I added a preliminary test for flatten function, but not for changes in trials table.
=> [dashboard/db page] DIsplay parameters in separated flattened columns after ID column

dashboard/src/src/experiments/content/DatabasePage/TrialTable.js
Hi @bouthilx ! This is a PR to display only first characters of trial ID in trials table.
- Display first 7 characters of a trail ID then 3 points
- Display full trial ID in a tooltip on mouseover
Since I am still unable to fix timeout issue for dashboarc tests, I have not added unit tests for these changes here.
=> [dashboard/DB page] Display only 7 first characters of trial ID in ID column.

dashboard/src/src/experiments/content/DatabasePage/DatabasePage.js, dashboard/src/src/experiments/content/DatabasePage/TrialTable.js
Hi @bouthilx ! This is a PR that allows to sort columns in experiment trials table.
- Allow to sort by clicking on column header
- A parameter column can be sorted either if parameter is not an array, or is an array with only 1 element in all trials.
=> [dashboard/experiments/database] make columns sortable, except non-singleton array columns

src/orion/core/io/experiment_builder.py, src/orion/core/worker/experiment.py, tests/unittests/core/worker/test_experiment.py
- Arguments are fully specified in `Experiment.__init__`. This is so we can avoid the current pattern of setting the attributes on the instance after it is initialized.
- Adds type annotations to the arguments of `Experiment.__init__` (and the attributes of `Experiment` objects), ~~with typed dictionaries for the `refers` and `metadata` attributes.~~ (Edit: Will be in another PR).
- Add type annotations to some of the functions in `experiment_builder.py`
- Raise a `UserWarning` if `experiment_builder.create_experiment` receives extra unused keyword arguments.
=> Minor refactor: Make creation of `Experiment` objects more explicit

src/orion/core/utils/tree.py
Minor refactor of the `PreOrderTraversal` and `DepthFirstTraversal` ~~classes~~ functions of `tree.py`.
=> Simplify tree.py

dashboard/src/src/__tests__/VisualizationsPage.test.js, dashboard/src/src/__tests__/experiments.databasePage.test.js, dashboard/src/src/experiments/components/ExperimentNavBar/ExperimentNavBar.js, dashboard/src/src/style.css
Hi @bouthilx ! This is a PR that removes (x) button in experiments navbar.
- Remove (x) button in experiments navbar
- Select experiment when we click on row (as usual), and deselect experiment if we re-click on same row (instead of x button)
- Selected experiment row is highlighted with gray background and bold font
- I also updated current tests in this PR, although CI will still not run here
=> [dashboard/experiments/navbar] Remove (x) icon on experiment menu and rely on highlight only

dashboard/src/package.json, dashboard/src/src/experiments/content/DatabasePage/DatabasePage.js, dashboard/src/src/experiments/content/DatabasePage/FeaturedTable.js, dashboard/src/yarn.lock
Hi @bouthilx ! This is a PR to use a new more featured table framework: https://tanstack.com/
- Use new framework tanstack/react-table
- Reimplement in new table:
- short names for trial IDs
- table sorting
- Implement in new table:
- grouped column for parameters
- pagination (combined with carbon-react pagination component)
- show/hide columns (use carbon-react multiselect component to choose displayed columns)
I guess a demo will be better to present changes ^^ !
=> [dashboard/experiments/database page] New table framework

docs/src/tutorials/pytorch-mnist.rst, docs/src/tutorials/scikit-learn.rst, examples/tutorials/code_1_python_api.py, examples/tutorials/code_2_hyperband_checkpoint.py
While doing the tutorials, some code wasn't running properly. This PR is basically to fix that.
Adding some imports to the tutorial for scikit,
Fixing a small argument mistake for pytorch,
adding if __name__ == '__main__': in python script so that they dont crash on macos.
- [ x] I added corresponding tests for bug fixes and new features. If possible, the tests fail without the changes
- [ x] I have updated the relevant documentation related to my changes
- [ x] I have read the [CONTRIBUTING](https://github.com/Epistimio/orion/blob/develop/CONTRIBUTING.md) doc
- [ x] My commits messages follow [this format](https://chris.beams.io/posts/git-commit/)
- [ x] My code follows the style guidelines (`$ tox -e lint`)
=> Fixing some details for the tutorials to run.

setup.py
Latest pandas version (1.5.0) has a compatibility issue with ax. Downgrading to 1.4.4 until it is fixed in ax.
=> Downgrade pandas temporarily

docs/src/user/config.rst, src/orion/client/__init__.py, src/orion/client/experiment.py, src/orion/core/__init__.py, src/orion/core/cli/hunt.py, tests/functional/configuration/test_all_options.py, tests/unittests/client/test_experiment_client.py, tests/unittests/core/io/test_resolve_config.py
Removing the deprecated reservation_timeout, using idle_timeout instead. Solving Github issue [reservation_timeout extra warning](https://github.com/Epistimio/orion/issues/1010)._
Changing reservation_timeout to idle_timout, or removing it if idle_timeout was already there.
- [ x] All new and existing tests are passing (`$ tox -e py38`; replace `38` by your Python version if necessary)
- [ x] I have updated the relevant documentation related to my changes
- [x ] I have read the [CONTRIBUTING](https://github.com/Epistimio/orion/blob/develop/CONTRIBUTING.md) doc
- [x ] My commits messages follow [this format](https://chris.beams.io/posts/git-commit/)
- [ x] My code follows the style guidelines (`$ tox -e lint`)
=> reservation_timeout removed

setup.py
GPy imports it all the time but does not list it as a dependency
See https://github.com/Epistimio/hydra_orion_sweeper/actions/runs/3330026395/jobs/5507981924#step:5:248
=> Add matplotlib dependency to pb2

conda/meta.yaml, setup.py
This was necessary because of an issue with Ax: https://github.com/Epistimio/orion/issues/999
But it is now fixed: https://github.com/facebook/Ax/releases/tag/0.2.8
=> Remove pandas version cap

src/orion/algo/asha/asha.py, src/orion/algo/base/base.py, src/orion/algo/evolution_es/evolution_es.py, src/orion/algo/pbt/pb2.py, src/orion/algo/pbt/pbt.py, src/orion/algo/tpe/tpe.py, tests/functional/algos/test_algos.py
Why:
There were no generic tests for nested spaces. Some of the base algo class methods were not handling nested spaces properly, in addition to 5 different algos.
How:
Add functional test with nested spaces, use flatten(trial.params) wherever it is used in algos as they all work on a flattened space.
=> Fix algos for nested spaces

src/orion/client/experiment.py, tests/unittests/client/test_experiment_client.py
Why:
Formatting results as dict(name, type, value) is cumbersome and the most common use case is observing a single result which is the objective. This use case should be simplified.
How:
Support `client.observe(trial, value, name)` and still support `client.observe(trial, results)`.
=> Make ExperimentClient.observe support single value

.pre-commit-config.yaml, docs/src/tutorials/huggingface.rst, examples/huggingface/config.yaml, examples/huggingface/main.py, examples/huggingface/requirements.txt
Writing a tutorial on how to use Orion with a HuggingFace model, including the use of the hydra_orion_sweeper, Comet and custom Callbacks.
Simply adding files in the docs and examples foldders.
- [x ] I have updated the relevant documentation related to my changes
- [ x] I have read the [CONTRIBUTING](https://github.com/Epistimio/orion/blob/develop/CONTRIBUTING.md) doc
- [ x] My commits messages follow [this format](https://chris.beams.io/posts/git-commit/)
- [ x] My code follows the style guidelines (`$ tox -e lint`)
=> Adding HuggingFace Tutorial

.github/workflows/dashboard-src.yml
Hi @bouthilx ! This is a small PR to make dashboard testing CI use local cloned repository instead of distant branch `git+https://github.com/notoraptor/orion.git@feature/benchmark_webapi_rebased#egg=orion[profet]` to run orion server. We should not need anymore to use a separate branch for server since benchmarks web API is now merged into `develop` branch.
- In Github Actions `dashboard-src.yml`, directly use local cloned repository to install Orion with extra `profet`
=> [ci] Install Orion from local cloned repository

.github/workflows/build.yml, conda/ci_build.sh, src/orion/core/cli/frontend.py
Hi @bouthilx ! This PR tries to fix #1083 . However, I don't know how to test it in CI. CI currently tests normal installation, but this issue seems related to a corner case, and I don't know how to reproduce it in CI.
t seems that, depending on installation, additional files may be installed in `<sys.prefix>/local` instead of just `<sys.prefix>`. More info: https://stackoverflow.com/questions/14211575/any-python-function-to-get-data-files-root-directory#comment99087548_14211600
So, this PR just checks both `<sys.prefix>` then `<sys.prefix>/local` to find dashboard build parent folder (named `orion-dashboard`).
On regular installations (e.g. in CI tests), checking `<sys.prefix>` is enough. But it seems data are installed in `<sys.prefix>/local` on Jupyter installations. I don't know why …
=> Fix detection of dashboard build files in installed packages.
